// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2015.4
// Copyright (C) 2015 Xilinx Inc. All rights reserved.
// 
// ===========================================================

#include "newsob.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_lv<8> newsob::ap_const_lv8_0 = "00000000";
const sc_lv<1> newsob::ap_const_lv1_0 = "0";
const sc_logic newsob::ap_const_logic_1 = sc_dt::Log_1;
const sc_logic newsob::ap_const_logic_0 = sc_dt::Log_0;
const bool newsob::ap_true = true;

newsob::newsob(sc_module_name name) : sc_module(name), mVcdFile(0) {
    newsob_Block_proc_U0 = new newsob_Block_proc("newsob_Block_proc_U0");
    newsob_Block_proc_U0->ap_clk(ap_clk);
    newsob_Block_proc_U0->ap_rst(ap_rst_n_inv);
    newsob_Block_proc_U0->ap_start(newsob_Block_proc_U0_ap_start);
    newsob_Block_proc_U0->ap_done(newsob_Block_proc_U0_ap_done);
    newsob_Block_proc_U0->ap_continue(newsob_Block_proc_U0_ap_continue);
    newsob_Block_proc_U0->ap_idle(newsob_Block_proc_U0_ap_idle);
    newsob_Block_proc_U0->ap_ready(newsob_Block_proc_U0_ap_ready);
    newsob_Block_proc_U0->img_0_rows_V_out_din(newsob_Block_proc_U0_img_0_rows_V_out_din);
    newsob_Block_proc_U0->img_0_rows_V_out_full_n(newsob_Block_proc_U0_img_0_rows_V_out_full_n);
    newsob_Block_proc_U0->img_0_rows_V_out_write(newsob_Block_proc_U0_img_0_rows_V_out_write);
    newsob_Block_proc_U0->img_0_cols_V_out_din(newsob_Block_proc_U0_img_0_cols_V_out_din);
    newsob_Block_proc_U0->img_0_cols_V_out_full_n(newsob_Block_proc_U0_img_0_cols_V_out_full_n);
    newsob_Block_proc_U0->img_0_cols_V_out_write(newsob_Block_proc_U0_img_0_cols_V_out_write);
    newsob_AXIvideo2Mat_DMA_U0 = new newsob_AXIvideo2Mat_DMA("newsob_AXIvideo2Mat_DMA_U0");
    newsob_AXIvideo2Mat_DMA_U0->ap_clk(ap_clk);
    newsob_AXIvideo2Mat_DMA_U0->ap_rst(ap_rst_n_inv);
    newsob_AXIvideo2Mat_DMA_U0->ap_start(newsob_AXIvideo2Mat_DMA_U0_ap_start);
    newsob_AXIvideo2Mat_DMA_U0->ap_done(newsob_AXIvideo2Mat_DMA_U0_ap_done);
    newsob_AXIvideo2Mat_DMA_U0->ap_continue(newsob_AXIvideo2Mat_DMA_U0_ap_continue);
    newsob_AXIvideo2Mat_DMA_U0->ap_idle(newsob_AXIvideo2Mat_DMA_U0_ap_idle);
    newsob_AXIvideo2Mat_DMA_U0->ap_ready(newsob_AXIvideo2Mat_DMA_U0_ap_ready);
    newsob_AXIvideo2Mat_DMA_U0->INPUT_STREAM_TDATA(newsob_AXIvideo2Mat_DMA_U0_INPUT_STREAM_TDATA);
    newsob_AXIvideo2Mat_DMA_U0->INPUT_STREAM_TVALID(newsob_AXIvideo2Mat_DMA_U0_INPUT_STREAM_TVALID);
    newsob_AXIvideo2Mat_DMA_U0->INPUT_STREAM_TREADY(newsob_AXIvideo2Mat_DMA_U0_INPUT_STREAM_TREADY);
    newsob_AXIvideo2Mat_DMA_U0->INPUT_STREAM_TKEEP(newsob_AXIvideo2Mat_DMA_U0_INPUT_STREAM_TKEEP);
    newsob_AXIvideo2Mat_DMA_U0->INPUT_STREAM_TSTRB(newsob_AXIvideo2Mat_DMA_U0_INPUT_STREAM_TSTRB);
    newsob_AXIvideo2Mat_DMA_U0->INPUT_STREAM_TUSER(newsob_AXIvideo2Mat_DMA_U0_INPUT_STREAM_TUSER);
    newsob_AXIvideo2Mat_DMA_U0->INPUT_STREAM_TLAST(newsob_AXIvideo2Mat_DMA_U0_INPUT_STREAM_TLAST);
    newsob_AXIvideo2Mat_DMA_U0->INPUT_STREAM_TID(newsob_AXIvideo2Mat_DMA_U0_INPUT_STREAM_TID);
    newsob_AXIvideo2Mat_DMA_U0->INPUT_STREAM_TDEST(newsob_AXIvideo2Mat_DMA_U0_INPUT_STREAM_TDEST);
    newsob_AXIvideo2Mat_DMA_U0->img_rows_V_dout(newsob_AXIvideo2Mat_DMA_U0_img_rows_V_dout);
    newsob_AXIvideo2Mat_DMA_U0->img_rows_V_empty_n(newsob_AXIvideo2Mat_DMA_U0_img_rows_V_empty_n);
    newsob_AXIvideo2Mat_DMA_U0->img_rows_V_read(newsob_AXIvideo2Mat_DMA_U0_img_rows_V_read);
    newsob_AXIvideo2Mat_DMA_U0->img_cols_V_dout(newsob_AXIvideo2Mat_DMA_U0_img_cols_V_dout);
    newsob_AXIvideo2Mat_DMA_U0->img_cols_V_empty_n(newsob_AXIvideo2Mat_DMA_U0_img_cols_V_empty_n);
    newsob_AXIvideo2Mat_DMA_U0->img_cols_V_read(newsob_AXIvideo2Mat_DMA_U0_img_cols_V_read);
    newsob_AXIvideo2Mat_DMA_U0->img_data_stream_V_din(newsob_AXIvideo2Mat_DMA_U0_img_data_stream_V_din);
    newsob_AXIvideo2Mat_DMA_U0->img_data_stream_V_full_n(newsob_AXIvideo2Mat_DMA_U0_img_data_stream_V_full_n);
    newsob_AXIvideo2Mat_DMA_U0->img_data_stream_V_write(newsob_AXIvideo2Mat_DMA_U0_img_data_stream_V_write);
    newsob_AXIvideo2Mat_DMA_U0->img_rows_V_out_din(newsob_AXIvideo2Mat_DMA_U0_img_rows_V_out_din);
    newsob_AXIvideo2Mat_DMA_U0->img_rows_V_out_full_n(newsob_AXIvideo2Mat_DMA_U0_img_rows_V_out_full_n);
    newsob_AXIvideo2Mat_DMA_U0->img_rows_V_out_write(newsob_AXIvideo2Mat_DMA_U0_img_rows_V_out_write);
    newsob_AXIvideo2Mat_DMA_U0->img_cols_V_out_din(newsob_AXIvideo2Mat_DMA_U0_img_cols_V_out_din);
    newsob_AXIvideo2Mat_DMA_U0->img_cols_V_out_full_n(newsob_AXIvideo2Mat_DMA_U0_img_cols_V_out_full_n);
    newsob_AXIvideo2Mat_DMA_U0->img_cols_V_out_write(newsob_AXIvideo2Mat_DMA_U0_img_cols_V_out_write);
    newsob_Sobel_U0 = new newsob_Sobel("newsob_Sobel_U0");
    newsob_Sobel_U0->ap_clk(ap_clk);
    newsob_Sobel_U0->ap_rst(ap_rst_n_inv);
    newsob_Sobel_U0->ap_start(newsob_Sobel_U0_ap_start);
    newsob_Sobel_U0->ap_done(newsob_Sobel_U0_ap_done);
    newsob_Sobel_U0->ap_continue(newsob_Sobel_U0_ap_continue);
    newsob_Sobel_U0->ap_idle(newsob_Sobel_U0_ap_idle);
    newsob_Sobel_U0->ap_ready(newsob_Sobel_U0_ap_ready);
    newsob_Sobel_U0->p_src_rows_V_dout(newsob_Sobel_U0_p_src_rows_V_dout);
    newsob_Sobel_U0->p_src_rows_V_empty_n(newsob_Sobel_U0_p_src_rows_V_empty_n);
    newsob_Sobel_U0->p_src_rows_V_read(newsob_Sobel_U0_p_src_rows_V_read);
    newsob_Sobel_U0->p_src_cols_V_dout(newsob_Sobel_U0_p_src_cols_V_dout);
    newsob_Sobel_U0->p_src_cols_V_empty_n(newsob_Sobel_U0_p_src_cols_V_empty_n);
    newsob_Sobel_U0->p_src_cols_V_read(newsob_Sobel_U0_p_src_cols_V_read);
    newsob_Sobel_U0->p_src_data_stream_V_dout(newsob_Sobel_U0_p_src_data_stream_V_dout);
    newsob_Sobel_U0->p_src_data_stream_V_empty_n(newsob_Sobel_U0_p_src_data_stream_V_empty_n);
    newsob_Sobel_U0->p_src_data_stream_V_read(newsob_Sobel_U0_p_src_data_stream_V_read);
    newsob_Sobel_U0->p_dst_data_stream_V_din(newsob_Sobel_U0_p_dst_data_stream_V_din);
    newsob_Sobel_U0->p_dst_data_stream_V_full_n(newsob_Sobel_U0_p_dst_data_stream_V_full_n);
    newsob_Sobel_U0->p_dst_data_stream_V_write(newsob_Sobel_U0_p_dst_data_stream_V_write);
    newsob_Mat2AXIvideo_DMA_U0 = new newsob_Mat2AXIvideo_DMA("newsob_Mat2AXIvideo_DMA_U0");
    newsob_Mat2AXIvideo_DMA_U0->ap_clk(ap_clk);
    newsob_Mat2AXIvideo_DMA_U0->ap_rst(ap_rst_n_inv);
    newsob_Mat2AXIvideo_DMA_U0->ap_start(newsob_Mat2AXIvideo_DMA_U0_ap_start);
    newsob_Mat2AXIvideo_DMA_U0->ap_done(newsob_Mat2AXIvideo_DMA_U0_ap_done);
    newsob_Mat2AXIvideo_DMA_U0->ap_continue(newsob_Mat2AXIvideo_DMA_U0_ap_continue);
    newsob_Mat2AXIvideo_DMA_U0->ap_idle(newsob_Mat2AXIvideo_DMA_U0_ap_idle);
    newsob_Mat2AXIvideo_DMA_U0->ap_ready(newsob_Mat2AXIvideo_DMA_U0_ap_ready);
    newsob_Mat2AXIvideo_DMA_U0->img_data_stream_V_dout(newsob_Mat2AXIvideo_DMA_U0_img_data_stream_V_dout);
    newsob_Mat2AXIvideo_DMA_U0->img_data_stream_V_empty_n(newsob_Mat2AXIvideo_DMA_U0_img_data_stream_V_empty_n);
    newsob_Mat2AXIvideo_DMA_U0->img_data_stream_V_read(newsob_Mat2AXIvideo_DMA_U0_img_data_stream_V_read);
    newsob_Mat2AXIvideo_DMA_U0->OUTPUT_STREAM_TDATA(newsob_Mat2AXIvideo_DMA_U0_OUTPUT_STREAM_TDATA);
    newsob_Mat2AXIvideo_DMA_U0->OUTPUT_STREAM_TVALID(newsob_Mat2AXIvideo_DMA_U0_OUTPUT_STREAM_TVALID);
    newsob_Mat2AXIvideo_DMA_U0->OUTPUT_STREAM_TREADY(newsob_Mat2AXIvideo_DMA_U0_OUTPUT_STREAM_TREADY);
    newsob_Mat2AXIvideo_DMA_U0->OUTPUT_STREAM_TKEEP(newsob_Mat2AXIvideo_DMA_U0_OUTPUT_STREAM_TKEEP);
    newsob_Mat2AXIvideo_DMA_U0->OUTPUT_STREAM_TSTRB(newsob_Mat2AXIvideo_DMA_U0_OUTPUT_STREAM_TSTRB);
    newsob_Mat2AXIvideo_DMA_U0->OUTPUT_STREAM_TUSER(newsob_Mat2AXIvideo_DMA_U0_OUTPUT_STREAM_TUSER);
    newsob_Mat2AXIvideo_DMA_U0->OUTPUT_STREAM_TLAST(newsob_Mat2AXIvideo_DMA_U0_OUTPUT_STREAM_TLAST);
    newsob_Mat2AXIvideo_DMA_U0->OUTPUT_STREAM_TID(newsob_Mat2AXIvideo_DMA_U0_OUTPUT_STREAM_TID);
    newsob_Mat2AXIvideo_DMA_U0->OUTPUT_STREAM_TDEST(newsob_Mat2AXIvideo_DMA_U0_OUTPUT_STREAM_TDEST);
    img_0_rows_V_channel_U = new FIFO_newsob_img_0_rows_V_channel("img_0_rows_V_channel_U");
    img_0_rows_V_channel_U->clk(ap_clk);
    img_0_rows_V_channel_U->reset(ap_rst_n_inv);
    img_0_rows_V_channel_U->if_read_ce(img_0_rows_V_channel_U_ap_dummy_ce);
    img_0_rows_V_channel_U->if_write_ce(img_0_rows_V_channel_U_ap_dummy_ce);
    img_0_rows_V_channel_U->if_din(img_0_rows_V_channel_din);
    img_0_rows_V_channel_U->if_full_n(img_0_rows_V_channel_full_n);
    img_0_rows_V_channel_U->if_write(img_0_rows_V_channel_write);
    img_0_rows_V_channel_U->if_dout(img_0_rows_V_channel_dout);
    img_0_rows_V_channel_U->if_empty_n(img_0_rows_V_channel_empty_n);
    img_0_rows_V_channel_U->if_read(img_0_rows_V_channel_read);
    img_0_cols_V_channel_U = new FIFO_newsob_img_0_cols_V_channel("img_0_cols_V_channel_U");
    img_0_cols_V_channel_U->clk(ap_clk);
    img_0_cols_V_channel_U->reset(ap_rst_n_inv);
    img_0_cols_V_channel_U->if_read_ce(img_0_cols_V_channel_U_ap_dummy_ce);
    img_0_cols_V_channel_U->if_write_ce(img_0_cols_V_channel_U_ap_dummy_ce);
    img_0_cols_V_channel_U->if_din(img_0_cols_V_channel_din);
    img_0_cols_V_channel_U->if_full_n(img_0_cols_V_channel_full_n);
    img_0_cols_V_channel_U->if_write(img_0_cols_V_channel_write);
    img_0_cols_V_channel_U->if_dout(img_0_cols_V_channel_dout);
    img_0_cols_V_channel_U->if_empty_n(img_0_cols_V_channel_empty_n);
    img_0_cols_V_channel_U->if_read(img_0_cols_V_channel_read);
    img_0_data_stream_0_V_U = new FIFO_newsob_img_0_data_stream_0_V("img_0_data_stream_0_V_U");
    img_0_data_stream_0_V_U->clk(ap_clk);
    img_0_data_stream_0_V_U->reset(ap_rst_n_inv);
    img_0_data_stream_0_V_U->if_read_ce(img_0_data_stream_0_V_U_ap_dummy_ce);
    img_0_data_stream_0_V_U->if_write_ce(img_0_data_stream_0_V_U_ap_dummy_ce);
    img_0_data_stream_0_V_U->if_din(img_0_data_stream_0_V_din);
    img_0_data_stream_0_V_U->if_full_n(img_0_data_stream_0_V_full_n);
    img_0_data_stream_0_V_U->if_write(img_0_data_stream_0_V_write);
    img_0_data_stream_0_V_U->if_dout(img_0_data_stream_0_V_dout);
    img_0_data_stream_0_V_U->if_empty_n(img_0_data_stream_0_V_empty_n);
    img_0_data_stream_0_V_U->if_read(img_0_data_stream_0_V_read);
    img_0_rows_V_channel5_U = new FIFO_newsob_img_0_rows_V_channel5("img_0_rows_V_channel5_U");
    img_0_rows_V_channel5_U->clk(ap_clk);
    img_0_rows_V_channel5_U->reset(ap_rst_n_inv);
    img_0_rows_V_channel5_U->if_read_ce(img_0_rows_V_channel5_U_ap_dummy_ce);
    img_0_rows_V_channel5_U->if_write_ce(img_0_rows_V_channel5_U_ap_dummy_ce);
    img_0_rows_V_channel5_U->if_din(img_0_rows_V_channel5_din);
    img_0_rows_V_channel5_U->if_full_n(img_0_rows_V_channel5_full_n);
    img_0_rows_V_channel5_U->if_write(img_0_rows_V_channel5_write);
    img_0_rows_V_channel5_U->if_dout(img_0_rows_V_channel5_dout);
    img_0_rows_V_channel5_U->if_empty_n(img_0_rows_V_channel5_empty_n);
    img_0_rows_V_channel5_U->if_read(img_0_rows_V_channel5_read);
    img_0_cols_V_channel6_U = new FIFO_newsob_img_0_cols_V_channel6("img_0_cols_V_channel6_U");
    img_0_cols_V_channel6_U->clk(ap_clk);
    img_0_cols_V_channel6_U->reset(ap_rst_n_inv);
    img_0_cols_V_channel6_U->if_read_ce(img_0_cols_V_channel6_U_ap_dummy_ce);
    img_0_cols_V_channel6_U->if_write_ce(img_0_cols_V_channel6_U_ap_dummy_ce);
    img_0_cols_V_channel6_U->if_din(img_0_cols_V_channel6_din);
    img_0_cols_V_channel6_U->if_full_n(img_0_cols_V_channel6_full_n);
    img_0_cols_V_channel6_U->if_write(img_0_cols_V_channel6_write);
    img_0_cols_V_channel6_U->if_dout(img_0_cols_V_channel6_dout);
    img_0_cols_V_channel6_U->if_empty_n(img_0_cols_V_channel6_empty_n);
    img_0_cols_V_channel6_U->if_read(img_0_cols_V_channel6_read);
    img_1_data_stream_0_V_U = new FIFO_newsob_img_1_data_stream_0_V("img_1_data_stream_0_V_U");
    img_1_data_stream_0_V_U->clk(ap_clk);
    img_1_data_stream_0_V_U->reset(ap_rst_n_inv);
    img_1_data_stream_0_V_U->if_read_ce(img_1_data_stream_0_V_U_ap_dummy_ce);
    img_1_data_stream_0_V_U->if_write_ce(img_1_data_stream_0_V_U_ap_dummy_ce);
    img_1_data_stream_0_V_U->if_din(img_1_data_stream_0_V_din);
    img_1_data_stream_0_V_U->if_full_n(img_1_data_stream_0_V_full_n);
    img_1_data_stream_0_V_U->if_write(img_1_data_stream_0_V_write);
    img_1_data_stream_0_V_U->if_dout(img_1_data_stream_0_V_dout);
    img_1_data_stream_0_V_U->if_empty_n(img_1_data_stream_0_V_empty_n);
    img_1_data_stream_0_V_U->if_read(img_1_data_stream_0_V_read);

    SC_METHOD(thread_ap_clk_no_reset_);
    dont_initialize();
    sensitive << ( ap_clk.pos() );

    SC_METHOD(thread_INPUT_STREAM_TREADY);
    sensitive << ( newsob_AXIvideo2Mat_DMA_U0_INPUT_STREAM_TREADY );

    SC_METHOD(thread_OUTPUT_STREAM_TDATA);
    sensitive << ( newsob_Mat2AXIvideo_DMA_U0_OUTPUT_STREAM_TDATA );

    SC_METHOD(thread_OUTPUT_STREAM_TDEST);
    sensitive << ( newsob_Mat2AXIvideo_DMA_U0_OUTPUT_STREAM_TDEST );

    SC_METHOD(thread_OUTPUT_STREAM_TID);
    sensitive << ( newsob_Mat2AXIvideo_DMA_U0_OUTPUT_STREAM_TID );

    SC_METHOD(thread_OUTPUT_STREAM_TKEEP);
    sensitive << ( newsob_Mat2AXIvideo_DMA_U0_OUTPUT_STREAM_TKEEP );

    SC_METHOD(thread_OUTPUT_STREAM_TLAST);
    sensitive << ( newsob_Mat2AXIvideo_DMA_U0_OUTPUT_STREAM_TLAST );

    SC_METHOD(thread_OUTPUT_STREAM_TSTRB);
    sensitive << ( newsob_Mat2AXIvideo_DMA_U0_OUTPUT_STREAM_TSTRB );

    SC_METHOD(thread_OUTPUT_STREAM_TUSER);
    sensitive << ( newsob_Mat2AXIvideo_DMA_U0_OUTPUT_STREAM_TUSER );

    SC_METHOD(thread_OUTPUT_STREAM_TVALID);
    sensitive << ( newsob_Mat2AXIvideo_DMA_U0_OUTPUT_STREAM_TVALID );

    SC_METHOD(thread_ap_done);
    sensitive << ( ap_sig_hs_done );

    SC_METHOD(thread_ap_idle);
    sensitive << ( newsob_Block_proc_U0_ap_idle );
    sensitive << ( newsob_AXIvideo2Mat_DMA_U0_ap_idle );
    sensitive << ( newsob_Sobel_U0_ap_idle );
    sensitive << ( newsob_Mat2AXIvideo_DMA_U0_ap_idle );

    SC_METHOD(thread_ap_ready);
    sensitive << ( ap_sig_top_allready );

    SC_METHOD(thread_ap_rst_n_inv);
    sensitive << ( ap_rst_n );

    SC_METHOD(thread_ap_sig_hs_continue);

    SC_METHOD(thread_ap_sig_hs_done);
    sensitive << ( newsob_Mat2AXIvideo_DMA_U0_ap_done );

    SC_METHOD(thread_ap_sig_top_allready);
    sensitive << ( newsob_AXIvideo2Mat_DMA_U0_ap_ready );

    SC_METHOD(thread_img_0_cols_V_channel6_U_ap_dummy_ce);

    SC_METHOD(thread_img_0_cols_V_channel6_din);
    sensitive << ( newsob_AXIvideo2Mat_DMA_U0_img_cols_V_out_din );

    SC_METHOD(thread_img_0_cols_V_channel6_read);
    sensitive << ( newsob_Sobel_U0_p_src_cols_V_read );

    SC_METHOD(thread_img_0_cols_V_channel6_write);
    sensitive << ( newsob_AXIvideo2Mat_DMA_U0_img_cols_V_out_write );

    SC_METHOD(thread_img_0_cols_V_channel_U_ap_dummy_ce);

    SC_METHOD(thread_img_0_cols_V_channel_din);
    sensitive << ( newsob_Block_proc_U0_img_0_cols_V_out_din );

    SC_METHOD(thread_img_0_cols_V_channel_read);
    sensitive << ( newsob_AXIvideo2Mat_DMA_U0_img_cols_V_read );

    SC_METHOD(thread_img_0_cols_V_channel_write);
    sensitive << ( newsob_Block_proc_U0_img_0_cols_V_out_write );

    SC_METHOD(thread_img_0_data_stream_0_V_U_ap_dummy_ce);

    SC_METHOD(thread_img_0_data_stream_0_V_din);
    sensitive << ( newsob_AXIvideo2Mat_DMA_U0_img_data_stream_V_din );

    SC_METHOD(thread_img_0_data_stream_0_V_read);
    sensitive << ( newsob_Sobel_U0_p_src_data_stream_V_read );

    SC_METHOD(thread_img_0_data_stream_0_V_write);
    sensitive << ( newsob_AXIvideo2Mat_DMA_U0_img_data_stream_V_write );

    SC_METHOD(thread_img_0_rows_V_channel5_U_ap_dummy_ce);

    SC_METHOD(thread_img_0_rows_V_channel5_din);
    sensitive << ( newsob_AXIvideo2Mat_DMA_U0_img_rows_V_out_din );

    SC_METHOD(thread_img_0_rows_V_channel5_read);
    sensitive << ( newsob_Sobel_U0_p_src_rows_V_read );

    SC_METHOD(thread_img_0_rows_V_channel5_write);
    sensitive << ( newsob_AXIvideo2Mat_DMA_U0_img_rows_V_out_write );

    SC_METHOD(thread_img_0_rows_V_channel_U_ap_dummy_ce);

    SC_METHOD(thread_img_0_rows_V_channel_din);
    sensitive << ( newsob_Block_proc_U0_img_0_rows_V_out_din );

    SC_METHOD(thread_img_0_rows_V_channel_read);
    sensitive << ( newsob_AXIvideo2Mat_DMA_U0_img_rows_V_read );

    SC_METHOD(thread_img_0_rows_V_channel_write);
    sensitive << ( newsob_Block_proc_U0_img_0_rows_V_out_write );

    SC_METHOD(thread_img_1_data_stream_0_V_U_ap_dummy_ce);

    SC_METHOD(thread_img_1_data_stream_0_V_din);
    sensitive << ( newsob_Sobel_U0_p_dst_data_stream_V_din );

    SC_METHOD(thread_img_1_data_stream_0_V_read);
    sensitive << ( newsob_Mat2AXIvideo_DMA_U0_img_data_stream_V_read );

    SC_METHOD(thread_img_1_data_stream_0_V_write);
    sensitive << ( newsob_Sobel_U0_p_dst_data_stream_V_write );

    SC_METHOD(thread_newsob_AXIvideo2Mat_DMA_U0_INPUT_STREAM_TDATA);
    sensitive << ( INPUT_STREAM_TDATA );

    SC_METHOD(thread_newsob_AXIvideo2Mat_DMA_U0_INPUT_STREAM_TDEST);
    sensitive << ( INPUT_STREAM_TDEST );

    SC_METHOD(thread_newsob_AXIvideo2Mat_DMA_U0_INPUT_STREAM_TID);
    sensitive << ( INPUT_STREAM_TID );

    SC_METHOD(thread_newsob_AXIvideo2Mat_DMA_U0_INPUT_STREAM_TKEEP);
    sensitive << ( INPUT_STREAM_TKEEP );

    SC_METHOD(thread_newsob_AXIvideo2Mat_DMA_U0_INPUT_STREAM_TLAST);
    sensitive << ( INPUT_STREAM_TLAST );

    SC_METHOD(thread_newsob_AXIvideo2Mat_DMA_U0_INPUT_STREAM_TSTRB);
    sensitive << ( INPUT_STREAM_TSTRB );

    SC_METHOD(thread_newsob_AXIvideo2Mat_DMA_U0_INPUT_STREAM_TUSER);
    sensitive << ( INPUT_STREAM_TUSER );

    SC_METHOD(thread_newsob_AXIvideo2Mat_DMA_U0_INPUT_STREAM_TVALID);
    sensitive << ( INPUT_STREAM_TVALID );

    SC_METHOD(thread_newsob_AXIvideo2Mat_DMA_U0_ap_continue);

    SC_METHOD(thread_newsob_AXIvideo2Mat_DMA_U0_ap_start);
    sensitive << ( ap_start );

    SC_METHOD(thread_newsob_AXIvideo2Mat_DMA_U0_img_cols_V_dout);
    sensitive << ( img_0_cols_V_channel_dout );

    SC_METHOD(thread_newsob_AXIvideo2Mat_DMA_U0_img_cols_V_empty_n);
    sensitive << ( img_0_cols_V_channel_empty_n );

    SC_METHOD(thread_newsob_AXIvideo2Mat_DMA_U0_img_cols_V_out_full_n);
    sensitive << ( img_0_cols_V_channel6_full_n );

    SC_METHOD(thread_newsob_AXIvideo2Mat_DMA_U0_img_data_stream_V_full_n);
    sensitive << ( img_0_data_stream_0_V_full_n );

    SC_METHOD(thread_newsob_AXIvideo2Mat_DMA_U0_img_rows_V_dout);
    sensitive << ( img_0_rows_V_channel_dout );

    SC_METHOD(thread_newsob_AXIvideo2Mat_DMA_U0_img_rows_V_empty_n);
    sensitive << ( img_0_rows_V_channel_empty_n );

    SC_METHOD(thread_newsob_AXIvideo2Mat_DMA_U0_img_rows_V_out_full_n);
    sensitive << ( img_0_rows_V_channel5_full_n );

    SC_METHOD(thread_newsob_Block_proc_U0_ap_continue);

    SC_METHOD(thread_newsob_Block_proc_U0_ap_start);
    sensitive << ( ap_start );

    SC_METHOD(thread_newsob_Block_proc_U0_img_0_cols_V_out_full_n);
    sensitive << ( img_0_cols_V_channel_full_n );

    SC_METHOD(thread_newsob_Block_proc_U0_img_0_rows_V_out_full_n);
    sensitive << ( img_0_rows_V_channel_full_n );

    SC_METHOD(thread_newsob_Mat2AXIvideo_DMA_U0_OUTPUT_STREAM_TREADY);
    sensitive << ( OUTPUT_STREAM_TREADY );

    SC_METHOD(thread_newsob_Mat2AXIvideo_DMA_U0_ap_continue);
    sensitive << ( ap_sig_hs_continue );

    SC_METHOD(thread_newsob_Mat2AXIvideo_DMA_U0_img_data_stream_V_dout);
    sensitive << ( img_1_data_stream_0_V_dout );

    SC_METHOD(thread_newsob_Mat2AXIvideo_DMA_U0_img_data_stream_V_empty_n);
    sensitive << ( img_1_data_stream_0_V_empty_n );

    SC_METHOD(thread_newsob_Sobel_U0_ap_continue);

    SC_METHOD(thread_newsob_Sobel_U0_p_dst_data_stream_V_full_n);
    sensitive << ( img_1_data_stream_0_V_full_n );

    SC_METHOD(thread_newsob_Sobel_U0_p_src_cols_V_dout);
    sensitive << ( img_0_cols_V_channel6_dout );

    SC_METHOD(thread_newsob_Sobel_U0_p_src_cols_V_empty_n);
    sensitive << ( img_0_cols_V_channel6_empty_n );

    SC_METHOD(thread_newsob_Sobel_U0_p_src_data_stream_V_dout);
    sensitive << ( img_0_data_stream_0_V_dout );

    SC_METHOD(thread_newsob_Sobel_U0_p_src_data_stream_V_empty_n);
    sensitive << ( img_0_data_stream_0_V_empty_n );

    SC_METHOD(thread_newsob_Sobel_U0_p_src_rows_V_dout);
    sensitive << ( img_0_rows_V_channel5_dout );

    SC_METHOD(thread_newsob_Sobel_U0_p_src_rows_V_empty_n);
    sensitive << ( img_0_rows_V_channel5_empty_n );

    SC_THREAD(thread_hdltv_gen);
    sensitive << ( ap_clk.pos() );

    newsob_Sobel_U0_ap_start = SC_LOGIC_0;
    newsob_Mat2AXIvideo_DMA_U0_ap_start = SC_LOGIC_0;
    ap_reg_procdone_newsob_Block_proc_U0 = SC_LOGIC_0;
    ap_reg_procdone_newsob_AXIvideo2Mat_DMA_U0 = SC_LOGIC_0;
    ap_reg_procdone_newsob_Sobel_U0 = SC_LOGIC_0;
    ap_reg_procdone_newsob_Mat2AXIvideo_DMA_U0 = SC_LOGIC_0;
    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "newsob_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT__
    sc_trace(mVcdFile, INPUT_STREAM_TDATA, "(port)INPUT_STREAM_TDATA");
    sc_trace(mVcdFile, INPUT_STREAM_TKEEP, "(port)INPUT_STREAM_TKEEP");
    sc_trace(mVcdFile, INPUT_STREAM_TSTRB, "(port)INPUT_STREAM_TSTRB");
    sc_trace(mVcdFile, INPUT_STREAM_TUSER, "(port)INPUT_STREAM_TUSER");
    sc_trace(mVcdFile, INPUT_STREAM_TLAST, "(port)INPUT_STREAM_TLAST");
    sc_trace(mVcdFile, INPUT_STREAM_TID, "(port)INPUT_STREAM_TID");
    sc_trace(mVcdFile, INPUT_STREAM_TDEST, "(port)INPUT_STREAM_TDEST");
    sc_trace(mVcdFile, OUTPUT_STREAM_TDATA, "(port)OUTPUT_STREAM_TDATA");
    sc_trace(mVcdFile, OUTPUT_STREAM_TKEEP, "(port)OUTPUT_STREAM_TKEEP");
    sc_trace(mVcdFile, OUTPUT_STREAM_TSTRB, "(port)OUTPUT_STREAM_TSTRB");
    sc_trace(mVcdFile, OUTPUT_STREAM_TUSER, "(port)OUTPUT_STREAM_TUSER");
    sc_trace(mVcdFile, OUTPUT_STREAM_TLAST, "(port)OUTPUT_STREAM_TLAST");
    sc_trace(mVcdFile, OUTPUT_STREAM_TID, "(port)OUTPUT_STREAM_TID");
    sc_trace(mVcdFile, OUTPUT_STREAM_TDEST, "(port)OUTPUT_STREAM_TDEST");
    sc_trace(mVcdFile, ap_clk, "(port)ap_clk");
    sc_trace(mVcdFile, ap_rst_n, "(port)ap_rst_n");
    sc_trace(mVcdFile, ap_start, "(port)ap_start");
    sc_trace(mVcdFile, INPUT_STREAM_TVALID, "(port)INPUT_STREAM_TVALID");
    sc_trace(mVcdFile, INPUT_STREAM_TREADY, "(port)INPUT_STREAM_TREADY");
    sc_trace(mVcdFile, OUTPUT_STREAM_TVALID, "(port)OUTPUT_STREAM_TVALID");
    sc_trace(mVcdFile, OUTPUT_STREAM_TREADY, "(port)OUTPUT_STREAM_TREADY");
    sc_trace(mVcdFile, ap_done, "(port)ap_done");
    sc_trace(mVcdFile, ap_idle, "(port)ap_idle");
    sc_trace(mVcdFile, ap_ready, "(port)ap_ready");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, ap_rst_n_inv, "ap_rst_n_inv");
    sc_trace(mVcdFile, newsob_Block_proc_U0_ap_start, "newsob_Block_proc_U0_ap_start");
    sc_trace(mVcdFile, newsob_Block_proc_U0_ap_done, "newsob_Block_proc_U0_ap_done");
    sc_trace(mVcdFile, newsob_Block_proc_U0_ap_continue, "newsob_Block_proc_U0_ap_continue");
    sc_trace(mVcdFile, newsob_Block_proc_U0_ap_idle, "newsob_Block_proc_U0_ap_idle");
    sc_trace(mVcdFile, newsob_Block_proc_U0_ap_ready, "newsob_Block_proc_U0_ap_ready");
    sc_trace(mVcdFile, newsob_Block_proc_U0_img_0_rows_V_out_din, "newsob_Block_proc_U0_img_0_rows_V_out_din");
    sc_trace(mVcdFile, newsob_Block_proc_U0_img_0_rows_V_out_full_n, "newsob_Block_proc_U0_img_0_rows_V_out_full_n");
    sc_trace(mVcdFile, newsob_Block_proc_U0_img_0_rows_V_out_write, "newsob_Block_proc_U0_img_0_rows_V_out_write");
    sc_trace(mVcdFile, newsob_Block_proc_U0_img_0_cols_V_out_din, "newsob_Block_proc_U0_img_0_cols_V_out_din");
    sc_trace(mVcdFile, newsob_Block_proc_U0_img_0_cols_V_out_full_n, "newsob_Block_proc_U0_img_0_cols_V_out_full_n");
    sc_trace(mVcdFile, newsob_Block_proc_U0_img_0_cols_V_out_write, "newsob_Block_proc_U0_img_0_cols_V_out_write");
    sc_trace(mVcdFile, newsob_AXIvideo2Mat_DMA_U0_ap_start, "newsob_AXIvideo2Mat_DMA_U0_ap_start");
    sc_trace(mVcdFile, newsob_AXIvideo2Mat_DMA_U0_ap_done, "newsob_AXIvideo2Mat_DMA_U0_ap_done");
    sc_trace(mVcdFile, newsob_AXIvideo2Mat_DMA_U0_ap_continue, "newsob_AXIvideo2Mat_DMA_U0_ap_continue");
    sc_trace(mVcdFile, newsob_AXIvideo2Mat_DMA_U0_ap_idle, "newsob_AXIvideo2Mat_DMA_U0_ap_idle");
    sc_trace(mVcdFile, newsob_AXIvideo2Mat_DMA_U0_ap_ready, "newsob_AXIvideo2Mat_DMA_U0_ap_ready");
    sc_trace(mVcdFile, newsob_AXIvideo2Mat_DMA_U0_INPUT_STREAM_TDATA, "newsob_AXIvideo2Mat_DMA_U0_INPUT_STREAM_TDATA");
    sc_trace(mVcdFile, newsob_AXIvideo2Mat_DMA_U0_INPUT_STREAM_TVALID, "newsob_AXIvideo2Mat_DMA_U0_INPUT_STREAM_TVALID");
    sc_trace(mVcdFile, newsob_AXIvideo2Mat_DMA_U0_INPUT_STREAM_TREADY, "newsob_AXIvideo2Mat_DMA_U0_INPUT_STREAM_TREADY");
    sc_trace(mVcdFile, newsob_AXIvideo2Mat_DMA_U0_INPUT_STREAM_TKEEP, "newsob_AXIvideo2Mat_DMA_U0_INPUT_STREAM_TKEEP");
    sc_trace(mVcdFile, newsob_AXIvideo2Mat_DMA_U0_INPUT_STREAM_TSTRB, "newsob_AXIvideo2Mat_DMA_U0_INPUT_STREAM_TSTRB");
    sc_trace(mVcdFile, newsob_AXIvideo2Mat_DMA_U0_INPUT_STREAM_TUSER, "newsob_AXIvideo2Mat_DMA_U0_INPUT_STREAM_TUSER");
    sc_trace(mVcdFile, newsob_AXIvideo2Mat_DMA_U0_INPUT_STREAM_TLAST, "newsob_AXIvideo2Mat_DMA_U0_INPUT_STREAM_TLAST");
    sc_trace(mVcdFile, newsob_AXIvideo2Mat_DMA_U0_INPUT_STREAM_TID, "newsob_AXIvideo2Mat_DMA_U0_INPUT_STREAM_TID");
    sc_trace(mVcdFile, newsob_AXIvideo2Mat_DMA_U0_INPUT_STREAM_TDEST, "newsob_AXIvideo2Mat_DMA_U0_INPUT_STREAM_TDEST");
    sc_trace(mVcdFile, newsob_AXIvideo2Mat_DMA_U0_img_rows_V_dout, "newsob_AXIvideo2Mat_DMA_U0_img_rows_V_dout");
    sc_trace(mVcdFile, newsob_AXIvideo2Mat_DMA_U0_img_rows_V_empty_n, "newsob_AXIvideo2Mat_DMA_U0_img_rows_V_empty_n");
    sc_trace(mVcdFile, newsob_AXIvideo2Mat_DMA_U0_img_rows_V_read, "newsob_AXIvideo2Mat_DMA_U0_img_rows_V_read");
    sc_trace(mVcdFile, newsob_AXIvideo2Mat_DMA_U0_img_cols_V_dout, "newsob_AXIvideo2Mat_DMA_U0_img_cols_V_dout");
    sc_trace(mVcdFile, newsob_AXIvideo2Mat_DMA_U0_img_cols_V_empty_n, "newsob_AXIvideo2Mat_DMA_U0_img_cols_V_empty_n");
    sc_trace(mVcdFile, newsob_AXIvideo2Mat_DMA_U0_img_cols_V_read, "newsob_AXIvideo2Mat_DMA_U0_img_cols_V_read");
    sc_trace(mVcdFile, newsob_AXIvideo2Mat_DMA_U0_img_data_stream_V_din, "newsob_AXIvideo2Mat_DMA_U0_img_data_stream_V_din");
    sc_trace(mVcdFile, newsob_AXIvideo2Mat_DMA_U0_img_data_stream_V_full_n, "newsob_AXIvideo2Mat_DMA_U0_img_data_stream_V_full_n");
    sc_trace(mVcdFile, newsob_AXIvideo2Mat_DMA_U0_img_data_stream_V_write, "newsob_AXIvideo2Mat_DMA_U0_img_data_stream_V_write");
    sc_trace(mVcdFile, newsob_AXIvideo2Mat_DMA_U0_img_rows_V_out_din, "newsob_AXIvideo2Mat_DMA_U0_img_rows_V_out_din");
    sc_trace(mVcdFile, newsob_AXIvideo2Mat_DMA_U0_img_rows_V_out_full_n, "newsob_AXIvideo2Mat_DMA_U0_img_rows_V_out_full_n");
    sc_trace(mVcdFile, newsob_AXIvideo2Mat_DMA_U0_img_rows_V_out_write, "newsob_AXIvideo2Mat_DMA_U0_img_rows_V_out_write");
    sc_trace(mVcdFile, newsob_AXIvideo2Mat_DMA_U0_img_cols_V_out_din, "newsob_AXIvideo2Mat_DMA_U0_img_cols_V_out_din");
    sc_trace(mVcdFile, newsob_AXIvideo2Mat_DMA_U0_img_cols_V_out_full_n, "newsob_AXIvideo2Mat_DMA_U0_img_cols_V_out_full_n");
    sc_trace(mVcdFile, newsob_AXIvideo2Mat_DMA_U0_img_cols_V_out_write, "newsob_AXIvideo2Mat_DMA_U0_img_cols_V_out_write");
    sc_trace(mVcdFile, newsob_Sobel_U0_ap_start, "newsob_Sobel_U0_ap_start");
    sc_trace(mVcdFile, newsob_Sobel_U0_ap_done, "newsob_Sobel_U0_ap_done");
    sc_trace(mVcdFile, newsob_Sobel_U0_ap_continue, "newsob_Sobel_U0_ap_continue");
    sc_trace(mVcdFile, newsob_Sobel_U0_ap_idle, "newsob_Sobel_U0_ap_idle");
    sc_trace(mVcdFile, newsob_Sobel_U0_ap_ready, "newsob_Sobel_U0_ap_ready");
    sc_trace(mVcdFile, newsob_Sobel_U0_p_src_rows_V_dout, "newsob_Sobel_U0_p_src_rows_V_dout");
    sc_trace(mVcdFile, newsob_Sobel_U0_p_src_rows_V_empty_n, "newsob_Sobel_U0_p_src_rows_V_empty_n");
    sc_trace(mVcdFile, newsob_Sobel_U0_p_src_rows_V_read, "newsob_Sobel_U0_p_src_rows_V_read");
    sc_trace(mVcdFile, newsob_Sobel_U0_p_src_cols_V_dout, "newsob_Sobel_U0_p_src_cols_V_dout");
    sc_trace(mVcdFile, newsob_Sobel_U0_p_src_cols_V_empty_n, "newsob_Sobel_U0_p_src_cols_V_empty_n");
    sc_trace(mVcdFile, newsob_Sobel_U0_p_src_cols_V_read, "newsob_Sobel_U0_p_src_cols_V_read");
    sc_trace(mVcdFile, newsob_Sobel_U0_p_src_data_stream_V_dout, "newsob_Sobel_U0_p_src_data_stream_V_dout");
    sc_trace(mVcdFile, newsob_Sobel_U0_p_src_data_stream_V_empty_n, "newsob_Sobel_U0_p_src_data_stream_V_empty_n");
    sc_trace(mVcdFile, newsob_Sobel_U0_p_src_data_stream_V_read, "newsob_Sobel_U0_p_src_data_stream_V_read");
    sc_trace(mVcdFile, newsob_Sobel_U0_p_dst_data_stream_V_din, "newsob_Sobel_U0_p_dst_data_stream_V_din");
    sc_trace(mVcdFile, newsob_Sobel_U0_p_dst_data_stream_V_full_n, "newsob_Sobel_U0_p_dst_data_stream_V_full_n");
    sc_trace(mVcdFile, newsob_Sobel_U0_p_dst_data_stream_V_write, "newsob_Sobel_U0_p_dst_data_stream_V_write");
    sc_trace(mVcdFile, newsob_Mat2AXIvideo_DMA_U0_ap_start, "newsob_Mat2AXIvideo_DMA_U0_ap_start");
    sc_trace(mVcdFile, newsob_Mat2AXIvideo_DMA_U0_ap_done, "newsob_Mat2AXIvideo_DMA_U0_ap_done");
    sc_trace(mVcdFile, newsob_Mat2AXIvideo_DMA_U0_ap_continue, "newsob_Mat2AXIvideo_DMA_U0_ap_continue");
    sc_trace(mVcdFile, newsob_Mat2AXIvideo_DMA_U0_ap_idle, "newsob_Mat2AXIvideo_DMA_U0_ap_idle");
    sc_trace(mVcdFile, newsob_Mat2AXIvideo_DMA_U0_ap_ready, "newsob_Mat2AXIvideo_DMA_U0_ap_ready");
    sc_trace(mVcdFile, newsob_Mat2AXIvideo_DMA_U0_img_data_stream_V_dout, "newsob_Mat2AXIvideo_DMA_U0_img_data_stream_V_dout");
    sc_trace(mVcdFile, newsob_Mat2AXIvideo_DMA_U0_img_data_stream_V_empty_n, "newsob_Mat2AXIvideo_DMA_U0_img_data_stream_V_empty_n");
    sc_trace(mVcdFile, newsob_Mat2AXIvideo_DMA_U0_img_data_stream_V_read, "newsob_Mat2AXIvideo_DMA_U0_img_data_stream_V_read");
    sc_trace(mVcdFile, newsob_Mat2AXIvideo_DMA_U0_OUTPUT_STREAM_TDATA, "newsob_Mat2AXIvideo_DMA_U0_OUTPUT_STREAM_TDATA");
    sc_trace(mVcdFile, newsob_Mat2AXIvideo_DMA_U0_OUTPUT_STREAM_TVALID, "newsob_Mat2AXIvideo_DMA_U0_OUTPUT_STREAM_TVALID");
    sc_trace(mVcdFile, newsob_Mat2AXIvideo_DMA_U0_OUTPUT_STREAM_TREADY, "newsob_Mat2AXIvideo_DMA_U0_OUTPUT_STREAM_TREADY");
    sc_trace(mVcdFile, newsob_Mat2AXIvideo_DMA_U0_OUTPUT_STREAM_TKEEP, "newsob_Mat2AXIvideo_DMA_U0_OUTPUT_STREAM_TKEEP");
    sc_trace(mVcdFile, newsob_Mat2AXIvideo_DMA_U0_OUTPUT_STREAM_TSTRB, "newsob_Mat2AXIvideo_DMA_U0_OUTPUT_STREAM_TSTRB");
    sc_trace(mVcdFile, newsob_Mat2AXIvideo_DMA_U0_OUTPUT_STREAM_TUSER, "newsob_Mat2AXIvideo_DMA_U0_OUTPUT_STREAM_TUSER");
    sc_trace(mVcdFile, newsob_Mat2AXIvideo_DMA_U0_OUTPUT_STREAM_TLAST, "newsob_Mat2AXIvideo_DMA_U0_OUTPUT_STREAM_TLAST");
    sc_trace(mVcdFile, newsob_Mat2AXIvideo_DMA_U0_OUTPUT_STREAM_TID, "newsob_Mat2AXIvideo_DMA_U0_OUTPUT_STREAM_TID");
    sc_trace(mVcdFile, newsob_Mat2AXIvideo_DMA_U0_OUTPUT_STREAM_TDEST, "newsob_Mat2AXIvideo_DMA_U0_OUTPUT_STREAM_TDEST");
    sc_trace(mVcdFile, ap_sig_hs_continue, "ap_sig_hs_continue");
    sc_trace(mVcdFile, img_0_rows_V_channel_U_ap_dummy_ce, "img_0_rows_V_channel_U_ap_dummy_ce");
    sc_trace(mVcdFile, img_0_rows_V_channel_din, "img_0_rows_V_channel_din");
    sc_trace(mVcdFile, img_0_rows_V_channel_full_n, "img_0_rows_V_channel_full_n");
    sc_trace(mVcdFile, img_0_rows_V_channel_write, "img_0_rows_V_channel_write");
    sc_trace(mVcdFile, img_0_rows_V_channel_dout, "img_0_rows_V_channel_dout");
    sc_trace(mVcdFile, img_0_rows_V_channel_empty_n, "img_0_rows_V_channel_empty_n");
    sc_trace(mVcdFile, img_0_rows_V_channel_read, "img_0_rows_V_channel_read");
    sc_trace(mVcdFile, img_0_cols_V_channel_U_ap_dummy_ce, "img_0_cols_V_channel_U_ap_dummy_ce");
    sc_trace(mVcdFile, img_0_cols_V_channel_din, "img_0_cols_V_channel_din");
    sc_trace(mVcdFile, img_0_cols_V_channel_full_n, "img_0_cols_V_channel_full_n");
    sc_trace(mVcdFile, img_0_cols_V_channel_write, "img_0_cols_V_channel_write");
    sc_trace(mVcdFile, img_0_cols_V_channel_dout, "img_0_cols_V_channel_dout");
    sc_trace(mVcdFile, img_0_cols_V_channel_empty_n, "img_0_cols_V_channel_empty_n");
    sc_trace(mVcdFile, img_0_cols_V_channel_read, "img_0_cols_V_channel_read");
    sc_trace(mVcdFile, img_0_data_stream_0_V_U_ap_dummy_ce, "img_0_data_stream_0_V_U_ap_dummy_ce");
    sc_trace(mVcdFile, img_0_data_stream_0_V_din, "img_0_data_stream_0_V_din");
    sc_trace(mVcdFile, img_0_data_stream_0_V_full_n, "img_0_data_stream_0_V_full_n");
    sc_trace(mVcdFile, img_0_data_stream_0_V_write, "img_0_data_stream_0_V_write");
    sc_trace(mVcdFile, img_0_data_stream_0_V_dout, "img_0_data_stream_0_V_dout");
    sc_trace(mVcdFile, img_0_data_stream_0_V_empty_n, "img_0_data_stream_0_V_empty_n");
    sc_trace(mVcdFile, img_0_data_stream_0_V_read, "img_0_data_stream_0_V_read");
    sc_trace(mVcdFile, img_0_rows_V_channel5_U_ap_dummy_ce, "img_0_rows_V_channel5_U_ap_dummy_ce");
    sc_trace(mVcdFile, img_0_rows_V_channel5_din, "img_0_rows_V_channel5_din");
    sc_trace(mVcdFile, img_0_rows_V_channel5_full_n, "img_0_rows_V_channel5_full_n");
    sc_trace(mVcdFile, img_0_rows_V_channel5_write, "img_0_rows_V_channel5_write");
    sc_trace(mVcdFile, img_0_rows_V_channel5_dout, "img_0_rows_V_channel5_dout");
    sc_trace(mVcdFile, img_0_rows_V_channel5_empty_n, "img_0_rows_V_channel5_empty_n");
    sc_trace(mVcdFile, img_0_rows_V_channel5_read, "img_0_rows_V_channel5_read");
    sc_trace(mVcdFile, img_0_cols_V_channel6_U_ap_dummy_ce, "img_0_cols_V_channel6_U_ap_dummy_ce");
    sc_trace(mVcdFile, img_0_cols_V_channel6_din, "img_0_cols_V_channel6_din");
    sc_trace(mVcdFile, img_0_cols_V_channel6_full_n, "img_0_cols_V_channel6_full_n");
    sc_trace(mVcdFile, img_0_cols_V_channel6_write, "img_0_cols_V_channel6_write");
    sc_trace(mVcdFile, img_0_cols_V_channel6_dout, "img_0_cols_V_channel6_dout");
    sc_trace(mVcdFile, img_0_cols_V_channel6_empty_n, "img_0_cols_V_channel6_empty_n");
    sc_trace(mVcdFile, img_0_cols_V_channel6_read, "img_0_cols_V_channel6_read");
    sc_trace(mVcdFile, img_1_data_stream_0_V_U_ap_dummy_ce, "img_1_data_stream_0_V_U_ap_dummy_ce");
    sc_trace(mVcdFile, img_1_data_stream_0_V_din, "img_1_data_stream_0_V_din");
    sc_trace(mVcdFile, img_1_data_stream_0_V_full_n, "img_1_data_stream_0_V_full_n");
    sc_trace(mVcdFile, img_1_data_stream_0_V_write, "img_1_data_stream_0_V_write");
    sc_trace(mVcdFile, img_1_data_stream_0_V_dout, "img_1_data_stream_0_V_dout");
    sc_trace(mVcdFile, img_1_data_stream_0_V_empty_n, "img_1_data_stream_0_V_empty_n");
    sc_trace(mVcdFile, img_1_data_stream_0_V_read, "img_1_data_stream_0_V_read");
    sc_trace(mVcdFile, ap_reg_procdone_newsob_Block_proc_U0, "ap_reg_procdone_newsob_Block_proc_U0");
    sc_trace(mVcdFile, ap_sig_hs_done, "ap_sig_hs_done");
    sc_trace(mVcdFile, ap_reg_procdone_newsob_AXIvideo2Mat_DMA_U0, "ap_reg_procdone_newsob_AXIvideo2Mat_DMA_U0");
    sc_trace(mVcdFile, ap_reg_procdone_newsob_Sobel_U0, "ap_reg_procdone_newsob_Sobel_U0");
    sc_trace(mVcdFile, ap_reg_procdone_newsob_Mat2AXIvideo_DMA_U0, "ap_reg_procdone_newsob_Mat2AXIvideo_DMA_U0");
    sc_trace(mVcdFile, ap_CS, "ap_CS");
    sc_trace(mVcdFile, ap_sig_top_allready, "ap_sig_top_allready");
#endif

    }
    mHdltvinHandle.open("newsob.hdltvin.dat");
    mHdltvoutHandle.open("newsob.hdltvout.dat");
}

newsob::~newsob() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

    mHdltvinHandle << "] " << endl;
    mHdltvoutHandle << "] " << endl;
    mHdltvinHandle.close();
    mHdltvoutHandle.close();
    delete newsob_Block_proc_U0;
    delete newsob_AXIvideo2Mat_DMA_U0;
    delete newsob_Sobel_U0;
    delete newsob_Mat2AXIvideo_DMA_U0;
    delete img_0_rows_V_channel_U;
    delete img_0_cols_V_channel_U;
    delete img_0_data_stream_0_V_U;
    delete img_0_rows_V_channel5_U;
    delete img_0_cols_V_channel6_U;
    delete img_1_data_stream_0_V_U;
}

void newsob::thread_ap_clk_no_reset_() {
    ap_CS = ap_const_logic_0;
    if ( ap_rst_n_inv.read() == ap_const_logic_1) {
        ap_reg_procdone_newsob_AXIvideo2Mat_DMA_U0 = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_hs_done.read())) {
            ap_reg_procdone_newsob_AXIvideo2Mat_DMA_U0 = ap_const_logic_0;
        } else if (esl_seteq<1,1,1>(ap_const_logic_1, newsob_AXIvideo2Mat_DMA_U0_ap_done.read())) {
            ap_reg_procdone_newsob_AXIvideo2Mat_DMA_U0 = ap_const_logic_1;
        }
    }
    if ( ap_rst_n_inv.read() == ap_const_logic_1) {
        ap_reg_procdone_newsob_Block_proc_U0 = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_hs_done.read())) {
            ap_reg_procdone_newsob_Block_proc_U0 = ap_const_logic_0;
        } else if (esl_seteq<1,1,1>(newsob_Block_proc_U0_ap_done.read(), ap_const_logic_1)) {
            ap_reg_procdone_newsob_Block_proc_U0 = ap_const_logic_1;
        }
    }
    if ( ap_rst_n_inv.read() == ap_const_logic_1) {
        ap_reg_procdone_newsob_Mat2AXIvideo_DMA_U0 = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_hs_done.read())) {
            ap_reg_procdone_newsob_Mat2AXIvideo_DMA_U0 = ap_const_logic_0;
        } else if (esl_seteq<1,1,1>(ap_const_logic_1, newsob_Mat2AXIvideo_DMA_U0_ap_done.read())) {
            ap_reg_procdone_newsob_Mat2AXIvideo_DMA_U0 = ap_const_logic_1;
        }
    }
    if ( ap_rst_n_inv.read() == ap_const_logic_1) {
        ap_reg_procdone_newsob_Sobel_U0 = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_hs_done.read())) {
            ap_reg_procdone_newsob_Sobel_U0 = ap_const_logic_0;
        } else if (esl_seteq<1,1,1>(ap_const_logic_1, newsob_Sobel_U0_ap_done.read())) {
            ap_reg_procdone_newsob_Sobel_U0 = ap_const_logic_1;
        }
    }
    if ( ap_rst_n_inv.read() == ap_const_logic_1) {
        newsob_Mat2AXIvideo_DMA_U0_ap_start = ap_const_logic_0;
    } else {
        newsob_Mat2AXIvideo_DMA_U0_ap_start = ap_const_logic_1;
    }
    if ( ap_rst_n_inv.read() == ap_const_logic_1) {
        newsob_Sobel_U0_ap_start = ap_const_logic_0;
    } else {
        newsob_Sobel_U0_ap_start = ap_const_logic_1;
    }
}

void newsob::thread_INPUT_STREAM_TREADY() {
    INPUT_STREAM_TREADY = newsob_AXIvideo2Mat_DMA_U0_INPUT_STREAM_TREADY.read();
}

void newsob::thread_OUTPUT_STREAM_TDATA() {
    OUTPUT_STREAM_TDATA = newsob_Mat2AXIvideo_DMA_U0_OUTPUT_STREAM_TDATA.read();
}

void newsob::thread_OUTPUT_STREAM_TDEST() {
    OUTPUT_STREAM_TDEST = newsob_Mat2AXIvideo_DMA_U0_OUTPUT_STREAM_TDEST.read();
}

void newsob::thread_OUTPUT_STREAM_TID() {
    OUTPUT_STREAM_TID = newsob_Mat2AXIvideo_DMA_U0_OUTPUT_STREAM_TID.read();
}

void newsob::thread_OUTPUT_STREAM_TKEEP() {
    OUTPUT_STREAM_TKEEP = newsob_Mat2AXIvideo_DMA_U0_OUTPUT_STREAM_TKEEP.read();
}

void newsob::thread_OUTPUT_STREAM_TLAST() {
    OUTPUT_STREAM_TLAST = newsob_Mat2AXIvideo_DMA_U0_OUTPUT_STREAM_TLAST.read();
}

void newsob::thread_OUTPUT_STREAM_TSTRB() {
    OUTPUT_STREAM_TSTRB = newsob_Mat2AXIvideo_DMA_U0_OUTPUT_STREAM_TSTRB.read();
}

void newsob::thread_OUTPUT_STREAM_TUSER() {
    OUTPUT_STREAM_TUSER = newsob_Mat2AXIvideo_DMA_U0_OUTPUT_STREAM_TUSER.read();
}

void newsob::thread_OUTPUT_STREAM_TVALID() {
    OUTPUT_STREAM_TVALID = newsob_Mat2AXIvideo_DMA_U0_OUTPUT_STREAM_TVALID.read();
}

void newsob::thread_ap_done() {
    ap_done = ap_sig_hs_done.read();
}

void newsob::thread_ap_idle() {
    if ((esl_seteq<1,1,1>(newsob_Block_proc_U0_ap_idle.read(), ap_const_logic_1) && 
         esl_seteq<1,1,1>(ap_const_logic_1, newsob_AXIvideo2Mat_DMA_U0_ap_idle.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, newsob_Sobel_U0_ap_idle.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, newsob_Mat2AXIvideo_DMA_U0_ap_idle.read()))) {
        ap_idle = ap_const_logic_1;
    } else {
        ap_idle = ap_const_logic_0;
    }
}

void newsob::thread_ap_ready() {
    ap_ready = ap_sig_top_allready.read();
}

void newsob::thread_ap_rst_n_inv() {
    ap_rst_n_inv =  (sc_logic) (~ap_rst_n.read());
}

void newsob::thread_ap_sig_hs_continue() {
    ap_sig_hs_continue = ap_const_logic_1;
}

void newsob::thread_ap_sig_hs_done() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, newsob_Mat2AXIvideo_DMA_U0_ap_done.read())) {
        ap_sig_hs_done = ap_const_logic_1;
    } else {
        ap_sig_hs_done = ap_const_logic_0;
    }
}

void newsob::thread_ap_sig_top_allready() {
    ap_sig_top_allready = newsob_AXIvideo2Mat_DMA_U0_ap_ready.read();
}

void newsob::thread_img_0_cols_V_channel6_U_ap_dummy_ce() {
    img_0_cols_V_channel6_U_ap_dummy_ce = ap_const_logic_1;
}

void newsob::thread_img_0_cols_V_channel6_din() {
    img_0_cols_V_channel6_din = newsob_AXIvideo2Mat_DMA_U0_img_cols_V_out_din.read();
}

void newsob::thread_img_0_cols_V_channel6_read() {
    img_0_cols_V_channel6_read = newsob_Sobel_U0_p_src_cols_V_read.read();
}

void newsob::thread_img_0_cols_V_channel6_write() {
    img_0_cols_V_channel6_write = newsob_AXIvideo2Mat_DMA_U0_img_cols_V_out_write.read();
}

void newsob::thread_img_0_cols_V_channel_U_ap_dummy_ce() {
    img_0_cols_V_channel_U_ap_dummy_ce = ap_const_logic_1;
}

void newsob::thread_img_0_cols_V_channel_din() {
    img_0_cols_V_channel_din = newsob_Block_proc_U0_img_0_cols_V_out_din.read();
}

void newsob::thread_img_0_cols_V_channel_read() {
    img_0_cols_V_channel_read = newsob_AXIvideo2Mat_DMA_U0_img_cols_V_read.read();
}

void newsob::thread_img_0_cols_V_channel_write() {
    img_0_cols_V_channel_write = newsob_Block_proc_U0_img_0_cols_V_out_write.read();
}

void newsob::thread_img_0_data_stream_0_V_U_ap_dummy_ce() {
    img_0_data_stream_0_V_U_ap_dummy_ce = ap_const_logic_1;
}

void newsob::thread_img_0_data_stream_0_V_din() {
    img_0_data_stream_0_V_din = newsob_AXIvideo2Mat_DMA_U0_img_data_stream_V_din.read();
}

void newsob::thread_img_0_data_stream_0_V_read() {
    img_0_data_stream_0_V_read = newsob_Sobel_U0_p_src_data_stream_V_read.read();
}

void newsob::thread_img_0_data_stream_0_V_write() {
    img_0_data_stream_0_V_write = newsob_AXIvideo2Mat_DMA_U0_img_data_stream_V_write.read();
}

void newsob::thread_img_0_rows_V_channel5_U_ap_dummy_ce() {
    img_0_rows_V_channel5_U_ap_dummy_ce = ap_const_logic_1;
}

void newsob::thread_img_0_rows_V_channel5_din() {
    img_0_rows_V_channel5_din = newsob_AXIvideo2Mat_DMA_U0_img_rows_V_out_din.read();
}

void newsob::thread_img_0_rows_V_channel5_read() {
    img_0_rows_V_channel5_read = newsob_Sobel_U0_p_src_rows_V_read.read();
}

void newsob::thread_img_0_rows_V_channel5_write() {
    img_0_rows_V_channel5_write = newsob_AXIvideo2Mat_DMA_U0_img_rows_V_out_write.read();
}

void newsob::thread_img_0_rows_V_channel_U_ap_dummy_ce() {
    img_0_rows_V_channel_U_ap_dummy_ce = ap_const_logic_1;
}

void newsob::thread_img_0_rows_V_channel_din() {
    img_0_rows_V_channel_din = newsob_Block_proc_U0_img_0_rows_V_out_din.read();
}

void newsob::thread_img_0_rows_V_channel_read() {
    img_0_rows_V_channel_read = newsob_AXIvideo2Mat_DMA_U0_img_rows_V_read.read();
}

void newsob::thread_img_0_rows_V_channel_write() {
    img_0_rows_V_channel_write = newsob_Block_proc_U0_img_0_rows_V_out_write.read();
}

void newsob::thread_img_1_data_stream_0_V_U_ap_dummy_ce() {
    img_1_data_stream_0_V_U_ap_dummy_ce = ap_const_logic_1;
}

void newsob::thread_img_1_data_stream_0_V_din() {
    img_1_data_stream_0_V_din = newsob_Sobel_U0_p_dst_data_stream_V_din.read();
}

void newsob::thread_img_1_data_stream_0_V_read() {
    img_1_data_stream_0_V_read = newsob_Mat2AXIvideo_DMA_U0_img_data_stream_V_read.read();
}

void newsob::thread_img_1_data_stream_0_V_write() {
    img_1_data_stream_0_V_write = newsob_Sobel_U0_p_dst_data_stream_V_write.read();
}

void newsob::thread_newsob_AXIvideo2Mat_DMA_U0_INPUT_STREAM_TDATA() {
    newsob_AXIvideo2Mat_DMA_U0_INPUT_STREAM_TDATA = INPUT_STREAM_TDATA.read();
}

void newsob::thread_newsob_AXIvideo2Mat_DMA_U0_INPUT_STREAM_TDEST() {
    newsob_AXIvideo2Mat_DMA_U0_INPUT_STREAM_TDEST = INPUT_STREAM_TDEST.read();
}

void newsob::thread_newsob_AXIvideo2Mat_DMA_U0_INPUT_STREAM_TID() {
    newsob_AXIvideo2Mat_DMA_U0_INPUT_STREAM_TID = INPUT_STREAM_TID.read();
}

void newsob::thread_newsob_AXIvideo2Mat_DMA_U0_INPUT_STREAM_TKEEP() {
    newsob_AXIvideo2Mat_DMA_U0_INPUT_STREAM_TKEEP = INPUT_STREAM_TKEEP.read();
}

void newsob::thread_newsob_AXIvideo2Mat_DMA_U0_INPUT_STREAM_TLAST() {
    newsob_AXIvideo2Mat_DMA_U0_INPUT_STREAM_TLAST = INPUT_STREAM_TLAST.read();
}

void newsob::thread_newsob_AXIvideo2Mat_DMA_U0_INPUT_STREAM_TSTRB() {
    newsob_AXIvideo2Mat_DMA_U0_INPUT_STREAM_TSTRB = INPUT_STREAM_TSTRB.read();
}

void newsob::thread_newsob_AXIvideo2Mat_DMA_U0_INPUT_STREAM_TUSER() {
    newsob_AXIvideo2Mat_DMA_U0_INPUT_STREAM_TUSER = INPUT_STREAM_TUSER.read();
}

void newsob::thread_newsob_AXIvideo2Mat_DMA_U0_INPUT_STREAM_TVALID() {
    newsob_AXIvideo2Mat_DMA_U0_INPUT_STREAM_TVALID = INPUT_STREAM_TVALID.read();
}

void newsob::thread_newsob_AXIvideo2Mat_DMA_U0_ap_continue() {
    newsob_AXIvideo2Mat_DMA_U0_ap_continue = ap_const_logic_1;
}

void newsob::thread_newsob_AXIvideo2Mat_DMA_U0_ap_start() {
    newsob_AXIvideo2Mat_DMA_U0_ap_start = ap_start.read();
}

void newsob::thread_newsob_AXIvideo2Mat_DMA_U0_img_cols_V_dout() {
    newsob_AXIvideo2Mat_DMA_U0_img_cols_V_dout = img_0_cols_V_channel_dout.read();
}

void newsob::thread_newsob_AXIvideo2Mat_DMA_U0_img_cols_V_empty_n() {
    newsob_AXIvideo2Mat_DMA_U0_img_cols_V_empty_n = img_0_cols_V_channel_empty_n.read();
}

void newsob::thread_newsob_AXIvideo2Mat_DMA_U0_img_cols_V_out_full_n() {
    newsob_AXIvideo2Mat_DMA_U0_img_cols_V_out_full_n = img_0_cols_V_channel6_full_n.read();
}

void newsob::thread_newsob_AXIvideo2Mat_DMA_U0_img_data_stream_V_full_n() {
    newsob_AXIvideo2Mat_DMA_U0_img_data_stream_V_full_n = img_0_data_stream_0_V_full_n.read();
}

void newsob::thread_newsob_AXIvideo2Mat_DMA_U0_img_rows_V_dout() {
    newsob_AXIvideo2Mat_DMA_U0_img_rows_V_dout = img_0_rows_V_channel_dout.read();
}

void newsob::thread_newsob_AXIvideo2Mat_DMA_U0_img_rows_V_empty_n() {
    newsob_AXIvideo2Mat_DMA_U0_img_rows_V_empty_n = img_0_rows_V_channel_empty_n.read();
}

void newsob::thread_newsob_AXIvideo2Mat_DMA_U0_img_rows_V_out_full_n() {
    newsob_AXIvideo2Mat_DMA_U0_img_rows_V_out_full_n = img_0_rows_V_channel5_full_n.read();
}

void newsob::thread_newsob_Block_proc_U0_ap_continue() {
    newsob_Block_proc_U0_ap_continue = ap_const_logic_1;
}

void newsob::thread_newsob_Block_proc_U0_ap_start() {
    newsob_Block_proc_U0_ap_start = ap_start.read();
}

void newsob::thread_newsob_Block_proc_U0_img_0_cols_V_out_full_n() {
    newsob_Block_proc_U0_img_0_cols_V_out_full_n = img_0_cols_V_channel_full_n.read();
}

void newsob::thread_newsob_Block_proc_U0_img_0_rows_V_out_full_n() {
    newsob_Block_proc_U0_img_0_rows_V_out_full_n = img_0_rows_V_channel_full_n.read();
}

void newsob::thread_newsob_Mat2AXIvideo_DMA_U0_OUTPUT_STREAM_TREADY() {
    newsob_Mat2AXIvideo_DMA_U0_OUTPUT_STREAM_TREADY = OUTPUT_STREAM_TREADY.read();
}

void newsob::thread_newsob_Mat2AXIvideo_DMA_U0_ap_continue() {
    newsob_Mat2AXIvideo_DMA_U0_ap_continue = ap_sig_hs_continue.read();
}

void newsob::thread_newsob_Mat2AXIvideo_DMA_U0_img_data_stream_V_dout() {
    newsob_Mat2AXIvideo_DMA_U0_img_data_stream_V_dout = img_1_data_stream_0_V_dout.read();
}

void newsob::thread_newsob_Mat2AXIvideo_DMA_U0_img_data_stream_V_empty_n() {
    newsob_Mat2AXIvideo_DMA_U0_img_data_stream_V_empty_n = img_1_data_stream_0_V_empty_n.read();
}

void newsob::thread_newsob_Sobel_U0_ap_continue() {
    newsob_Sobel_U0_ap_continue = ap_const_logic_1;
}

void newsob::thread_newsob_Sobel_U0_p_dst_data_stream_V_full_n() {
    newsob_Sobel_U0_p_dst_data_stream_V_full_n = img_1_data_stream_0_V_full_n.read();
}

void newsob::thread_newsob_Sobel_U0_p_src_cols_V_dout() {
    newsob_Sobel_U0_p_src_cols_V_dout = img_0_cols_V_channel6_dout.read();
}

void newsob::thread_newsob_Sobel_U0_p_src_cols_V_empty_n() {
    newsob_Sobel_U0_p_src_cols_V_empty_n = img_0_cols_V_channel6_empty_n.read();
}

void newsob::thread_newsob_Sobel_U0_p_src_data_stream_V_dout() {
    newsob_Sobel_U0_p_src_data_stream_V_dout = img_0_data_stream_0_V_dout.read();
}

void newsob::thread_newsob_Sobel_U0_p_src_data_stream_V_empty_n() {
    newsob_Sobel_U0_p_src_data_stream_V_empty_n = img_0_data_stream_0_V_empty_n.read();
}

void newsob::thread_newsob_Sobel_U0_p_src_rows_V_dout() {
    newsob_Sobel_U0_p_src_rows_V_dout = img_0_rows_V_channel5_dout.read();
}

void newsob::thread_newsob_Sobel_U0_p_src_rows_V_empty_n() {
    newsob_Sobel_U0_p_src_rows_V_empty_n = img_0_rows_V_channel5_empty_n.read();
}

void newsob::thread_hdltv_gen() {
    const char* dump_tv = std::getenv("AP_WRITE_TV");
    if (!(dump_tv && string(dump_tv) == "on")) return;

    wait();

    mHdltvinHandle << "[ " << endl;
    mHdltvoutHandle << "[ " << endl;
    int ap_cycleNo = 0;
    while (1) {
        wait();
        const char* mComma = ap_cycleNo == 0 ? " " : ", " ;
        mHdltvinHandle << mComma << "{"  <<  " \"INPUT_STREAM_TDATA\" :  \"" << INPUT_STREAM_TDATA.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"INPUT_STREAM_TKEEP\" :  \"" << INPUT_STREAM_TKEEP.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"INPUT_STREAM_TSTRB\" :  \"" << INPUT_STREAM_TSTRB.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"INPUT_STREAM_TUSER\" :  \"" << INPUT_STREAM_TUSER.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"INPUT_STREAM_TLAST\" :  \"" << INPUT_STREAM_TLAST.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"INPUT_STREAM_TID\" :  \"" << INPUT_STREAM_TID.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"INPUT_STREAM_TDEST\" :  \"" << INPUT_STREAM_TDEST.read() << "\" ";
        mHdltvoutHandle << mComma << "{"  <<  " \"OUTPUT_STREAM_TDATA\" :  \"" << OUTPUT_STREAM_TDATA.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"OUTPUT_STREAM_TKEEP\" :  \"" << OUTPUT_STREAM_TKEEP.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"OUTPUT_STREAM_TSTRB\" :  \"" << OUTPUT_STREAM_TSTRB.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"OUTPUT_STREAM_TUSER\" :  \"" << OUTPUT_STREAM_TUSER.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"OUTPUT_STREAM_TLAST\" :  \"" << OUTPUT_STREAM_TLAST.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"OUTPUT_STREAM_TID\" :  \"" << OUTPUT_STREAM_TID.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"OUTPUT_STREAM_TDEST\" :  \"" << OUTPUT_STREAM_TDEST.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"ap_rst_n\" :  \"" << ap_rst_n.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"ap_start\" :  \"" << ap_start.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"INPUT_STREAM_TVALID\" :  \"" << INPUT_STREAM_TVALID.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"INPUT_STREAM_TREADY\" :  \"" << INPUT_STREAM_TREADY.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"OUTPUT_STREAM_TVALID\" :  \"" << OUTPUT_STREAM_TVALID.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"OUTPUT_STREAM_TREADY\" :  \"" << OUTPUT_STREAM_TREADY.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"ap_done\" :  \"" << ap_done.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"ap_idle\" :  \"" << ap_idle.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"ap_ready\" :  \"" << ap_ready.read() << "\" ";
        mHdltvinHandle << "}" << std::endl;
        mHdltvoutHandle << "}" << std::endl;
        ap_cycleNo++;
    }
}

}

