// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2015.4
// Copyright (C) 2015 Xilinx Inc. All rights reserved.
// 
// ===========================================================

#include "newsob_AXIvideo2Mat_DMA.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_logic newsob_AXIvideo2Mat_DMA::ap_const_logic_1 = sc_dt::Log_1;
const sc_logic newsob_AXIvideo2Mat_DMA::ap_const_logic_0 = sc_dt::Log_0;
const sc_lv<4> newsob_AXIvideo2Mat_DMA::ap_ST_st1_fsm_0 = "1";
const sc_lv<4> newsob_AXIvideo2Mat_DMA::ap_ST_st2_fsm_1 = "10";
const sc_lv<4> newsob_AXIvideo2Mat_DMA::ap_ST_pp0_stg0_fsm_2 = "100";
const sc_lv<4> newsob_AXIvideo2Mat_DMA::ap_ST_st5_fsm_3 = "1000";
const sc_lv<32> newsob_AXIvideo2Mat_DMA::ap_const_lv32_0 = "00000000000000000000000000000000";
const sc_lv<1> newsob_AXIvideo2Mat_DMA::ap_const_lv1_1 = "1";
const sc_lv<32> newsob_AXIvideo2Mat_DMA::ap_const_lv32_1 = "1";
const sc_lv<32> newsob_AXIvideo2Mat_DMA::ap_const_lv32_2 = "10";
const sc_lv<1> newsob_AXIvideo2Mat_DMA::ap_const_lv1_0 = "0";
const sc_lv<12> newsob_AXIvideo2Mat_DMA::ap_const_lv12_0 = "000000000000";
const sc_lv<32> newsob_AXIvideo2Mat_DMA::ap_const_lv32_3 = "11";
const sc_lv<12> newsob_AXIvideo2Mat_DMA::ap_const_lv12_1 = "1";

newsob_AXIvideo2Mat_DMA::newsob_AXIvideo2Mat_DMA(sc_module_name name) : sc_module(name), mVcdFile(0) {

    SC_METHOD(thread_ap_clk_no_reset_);
    dont_initialize();
    sensitive << ( ap_clk.pos() );

    SC_METHOD(thread_INPUT_STREAM_TREADY);
    sensitive << ( exitcond_i_fu_158_p2 );
    sensitive << ( ap_sig_cseq_ST_pp0_stg0_fsm_2 );
    sensitive << ( ap_sig_bdd_103 );
    sensitive << ( ap_reg_ppiten_pp0_it0 );
    sensitive << ( ap_sig_bdd_110 );
    sensitive << ( ap_reg_ppiten_pp0_it1 );

    SC_METHOD(thread_ap_done);
    sensitive << ( ap_done_reg );
    sensitive << ( exitcond5_i_fu_147_p2 );
    sensitive << ( ap_sig_cseq_ST_st2_fsm_1 );

    SC_METHOD(thread_ap_idle);
    sensitive << ( ap_start );
    sensitive << ( ap_sig_cseq_ST_st1_fsm_0 );

    SC_METHOD(thread_ap_ready);
    sensitive << ( exitcond5_i_fu_147_p2 );
    sensitive << ( ap_sig_cseq_ST_st2_fsm_1 );

    SC_METHOD(thread_ap_sig_bdd_103);
    sensitive << ( INPUT_STREAM_TVALID );
    sensitive << ( exitcond_i_fu_158_p2 );

    SC_METHOD(thread_ap_sig_bdd_110);
    sensitive << ( img_data_stream_V_full_n );
    sensitive << ( exitcond_i_reg_192 );

    SC_METHOD(thread_ap_sig_bdd_137);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_bdd_23);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_bdd_74);
    sensitive << ( ap_start );
    sensitive << ( ap_done_reg );
    sensitive << ( img_rows_V_empty_n );
    sensitive << ( img_cols_V_empty_n );
    sensitive << ( img_rows_V_out_full_n );
    sensitive << ( img_cols_V_out_full_n );

    SC_METHOD(thread_ap_sig_bdd_86);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_bdd_97);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_cseq_ST_pp0_stg0_fsm_2);
    sensitive << ( ap_sig_bdd_97 );

    SC_METHOD(thread_ap_sig_cseq_ST_st1_fsm_0);
    sensitive << ( ap_sig_bdd_23 );

    SC_METHOD(thread_ap_sig_cseq_ST_st2_fsm_1);
    sensitive << ( ap_sig_bdd_86 );

    SC_METHOD(thread_ap_sig_cseq_ST_st5_fsm_3);
    sensitive << ( ap_sig_bdd_137 );

    SC_METHOD(thread_exitcond5_i_fu_147_p2);
    sensitive << ( rows_V_reg_173 );
    sensitive << ( ap_sig_cseq_ST_st2_fsm_1 );
    sensitive << ( p_1_i_reg_125 );

    SC_METHOD(thread_exitcond_i_fu_158_p2);
    sensitive << ( p_i_reg_136 );
    sensitive << ( cols_V_reg_178 );
    sensitive << ( ap_sig_cseq_ST_pp0_stg0_fsm_2 );
    sensitive << ( ap_sig_bdd_103 );
    sensitive << ( ap_reg_ppiten_pp0_it0 );
    sensitive << ( ap_sig_bdd_110 );
    sensitive << ( ap_reg_ppiten_pp0_it1 );

    SC_METHOD(thread_i_V_fu_152_p2);
    sensitive << ( p_1_i_reg_125 );

    SC_METHOD(thread_img_cols_V_out_din);
    sensitive << ( ap_sig_cseq_ST_st1_fsm_0 );
    sensitive << ( img_cols_V_dout );
    sensitive << ( ap_sig_bdd_74 );

    SC_METHOD(thread_img_cols_V_out_write);
    sensitive << ( ap_sig_cseq_ST_st1_fsm_0 );
    sensitive << ( ap_sig_bdd_74 );

    SC_METHOD(thread_img_cols_V_read);
    sensitive << ( ap_sig_cseq_ST_st1_fsm_0 );
    sensitive << ( ap_sig_bdd_74 );

    SC_METHOD(thread_img_data_stream_V_din);
    sensitive << ( exitcond_i_reg_192 );
    sensitive << ( ap_sig_cseq_ST_pp0_stg0_fsm_2 );
    sensitive << ( ap_sig_bdd_103 );
    sensitive << ( ap_reg_ppiten_pp0_it0 );
    sensitive << ( ap_sig_bdd_110 );
    sensitive << ( ap_reg_ppiten_pp0_it1 );
    sensitive << ( tmp_data_V_reg_201 );

    SC_METHOD(thread_img_data_stream_V_write);
    sensitive << ( exitcond_i_reg_192 );
    sensitive << ( ap_sig_cseq_ST_pp0_stg0_fsm_2 );
    sensitive << ( ap_sig_bdd_103 );
    sensitive << ( ap_reg_ppiten_pp0_it0 );
    sensitive << ( ap_sig_bdd_110 );
    sensitive << ( ap_reg_ppiten_pp0_it1 );

    SC_METHOD(thread_img_rows_V_out_din);
    sensitive << ( ap_sig_cseq_ST_st1_fsm_0 );
    sensitive << ( img_rows_V_dout );
    sensitive << ( ap_sig_bdd_74 );

    SC_METHOD(thread_img_rows_V_out_write);
    sensitive << ( ap_sig_cseq_ST_st1_fsm_0 );
    sensitive << ( ap_sig_bdd_74 );

    SC_METHOD(thread_img_rows_V_read);
    sensitive << ( ap_sig_cseq_ST_st1_fsm_0 );
    sensitive << ( ap_sig_bdd_74 );

    SC_METHOD(thread_j_V_fu_163_p2);
    sensitive << ( p_i_reg_136 );

    SC_METHOD(thread_ap_NS_fsm);
    sensitive << ( ap_CS_fsm );
    sensitive << ( ap_sig_bdd_74 );
    sensitive << ( exitcond5_i_fu_147_p2 );
    sensitive << ( exitcond_i_fu_158_p2 );
    sensitive << ( ap_sig_bdd_103 );
    sensitive << ( ap_reg_ppiten_pp0_it0 );
    sensitive << ( ap_sig_bdd_110 );
    sensitive << ( ap_reg_ppiten_pp0_it1 );

    ap_done_reg = SC_LOGIC_0;
    ap_CS_fsm = "0001";
    ap_reg_ppiten_pp0_it0 = SC_LOGIC_0;
    ap_reg_ppiten_pp0_it1 = SC_LOGIC_0;
    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "newsob_AXIvideo2Mat_DMA_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT_HIER__
    sc_trace(mVcdFile, ap_clk, "(port)ap_clk");
    sc_trace(mVcdFile, ap_rst, "(port)ap_rst");
    sc_trace(mVcdFile, ap_start, "(port)ap_start");
    sc_trace(mVcdFile, ap_done, "(port)ap_done");
    sc_trace(mVcdFile, ap_continue, "(port)ap_continue");
    sc_trace(mVcdFile, ap_idle, "(port)ap_idle");
    sc_trace(mVcdFile, ap_ready, "(port)ap_ready");
    sc_trace(mVcdFile, INPUT_STREAM_TDATA, "(port)INPUT_STREAM_TDATA");
    sc_trace(mVcdFile, INPUT_STREAM_TVALID, "(port)INPUT_STREAM_TVALID");
    sc_trace(mVcdFile, INPUT_STREAM_TREADY, "(port)INPUT_STREAM_TREADY");
    sc_trace(mVcdFile, INPUT_STREAM_TKEEP, "(port)INPUT_STREAM_TKEEP");
    sc_trace(mVcdFile, INPUT_STREAM_TSTRB, "(port)INPUT_STREAM_TSTRB");
    sc_trace(mVcdFile, INPUT_STREAM_TUSER, "(port)INPUT_STREAM_TUSER");
    sc_trace(mVcdFile, INPUT_STREAM_TLAST, "(port)INPUT_STREAM_TLAST");
    sc_trace(mVcdFile, INPUT_STREAM_TID, "(port)INPUT_STREAM_TID");
    sc_trace(mVcdFile, INPUT_STREAM_TDEST, "(port)INPUT_STREAM_TDEST");
    sc_trace(mVcdFile, img_rows_V_dout, "(port)img_rows_V_dout");
    sc_trace(mVcdFile, img_rows_V_empty_n, "(port)img_rows_V_empty_n");
    sc_trace(mVcdFile, img_rows_V_read, "(port)img_rows_V_read");
    sc_trace(mVcdFile, img_cols_V_dout, "(port)img_cols_V_dout");
    sc_trace(mVcdFile, img_cols_V_empty_n, "(port)img_cols_V_empty_n");
    sc_trace(mVcdFile, img_cols_V_read, "(port)img_cols_V_read");
    sc_trace(mVcdFile, img_data_stream_V_din, "(port)img_data_stream_V_din");
    sc_trace(mVcdFile, img_data_stream_V_full_n, "(port)img_data_stream_V_full_n");
    sc_trace(mVcdFile, img_data_stream_V_write, "(port)img_data_stream_V_write");
    sc_trace(mVcdFile, img_rows_V_out_din, "(port)img_rows_V_out_din");
    sc_trace(mVcdFile, img_rows_V_out_full_n, "(port)img_rows_V_out_full_n");
    sc_trace(mVcdFile, img_rows_V_out_write, "(port)img_rows_V_out_write");
    sc_trace(mVcdFile, img_cols_V_out_din, "(port)img_cols_V_out_din");
    sc_trace(mVcdFile, img_cols_V_out_full_n, "(port)img_cols_V_out_full_n");
    sc_trace(mVcdFile, img_cols_V_out_write, "(port)img_cols_V_out_write");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, ap_done_reg, "ap_done_reg");
    sc_trace(mVcdFile, ap_CS_fsm, "ap_CS_fsm");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st1_fsm_0, "ap_sig_cseq_ST_st1_fsm_0");
    sc_trace(mVcdFile, ap_sig_bdd_23, "ap_sig_bdd_23");
    sc_trace(mVcdFile, p_i_reg_136, "p_i_reg_136");
    sc_trace(mVcdFile, rows_V_reg_173, "rows_V_reg_173");
    sc_trace(mVcdFile, ap_sig_bdd_74, "ap_sig_bdd_74");
    sc_trace(mVcdFile, cols_V_reg_178, "cols_V_reg_178");
    sc_trace(mVcdFile, exitcond5_i_fu_147_p2, "exitcond5_i_fu_147_p2");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st2_fsm_1, "ap_sig_cseq_ST_st2_fsm_1");
    sc_trace(mVcdFile, ap_sig_bdd_86, "ap_sig_bdd_86");
    sc_trace(mVcdFile, i_V_fu_152_p2, "i_V_fu_152_p2");
    sc_trace(mVcdFile, i_V_reg_187, "i_V_reg_187");
    sc_trace(mVcdFile, exitcond_i_fu_158_p2, "exitcond_i_fu_158_p2");
    sc_trace(mVcdFile, exitcond_i_reg_192, "exitcond_i_reg_192");
    sc_trace(mVcdFile, ap_sig_cseq_ST_pp0_stg0_fsm_2, "ap_sig_cseq_ST_pp0_stg0_fsm_2");
    sc_trace(mVcdFile, ap_sig_bdd_97, "ap_sig_bdd_97");
    sc_trace(mVcdFile, ap_sig_bdd_103, "ap_sig_bdd_103");
    sc_trace(mVcdFile, ap_reg_ppiten_pp0_it0, "ap_reg_ppiten_pp0_it0");
    sc_trace(mVcdFile, ap_sig_bdd_110, "ap_sig_bdd_110");
    sc_trace(mVcdFile, ap_reg_ppiten_pp0_it1, "ap_reg_ppiten_pp0_it1");
    sc_trace(mVcdFile, j_V_fu_163_p2, "j_V_fu_163_p2");
    sc_trace(mVcdFile, tmp_data_V_reg_201, "tmp_data_V_reg_201");
    sc_trace(mVcdFile, p_1_i_reg_125, "p_1_i_reg_125");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st5_fsm_3, "ap_sig_cseq_ST_st5_fsm_3");
    sc_trace(mVcdFile, ap_sig_bdd_137, "ap_sig_bdd_137");
    sc_trace(mVcdFile, ap_NS_fsm, "ap_NS_fsm");
#endif

    }
}

newsob_AXIvideo2Mat_DMA::~newsob_AXIvideo2Mat_DMA() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

}

void newsob_AXIvideo2Mat_DMA::thread_ap_clk_no_reset_() {
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_CS_fsm = ap_ST_st1_fsm_0;
    } else {
        ap_CS_fsm = ap_NS_fsm.read();
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_done_reg = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_const_logic_1, ap_continue.read())) {
            ap_done_reg = ap_const_logic_0;
        } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st2_fsm_1.read()) && 
                    !esl_seteq<1,1,1>(exitcond5_i_fu_147_p2.read(), ap_const_lv1_0))) {
            ap_done_reg = ap_const_logic_1;
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_reg_ppiten_pp0_it0 = ap_const_logic_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg0_fsm_2.read()) && 
             !((ap_sig_bdd_103.read() && 
  esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it0.read())) || (ap_sig_bdd_110.read() && 
  esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read()))) && 
             !esl_seteq<1,1,1>(exitcond_i_fu_158_p2.read(), ap_const_lv1_0))) {
            ap_reg_ppiten_pp0_it0 = ap_const_logic_0;
        } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st2_fsm_1.read()) && 
                    esl_seteq<1,1,1>(exitcond5_i_fu_147_p2.read(), ap_const_lv1_0))) {
            ap_reg_ppiten_pp0_it0 = ap_const_logic_1;
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_reg_ppiten_pp0_it1 = ap_const_logic_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg0_fsm_2.read()) && 
             esl_seteq<1,1,1>(exitcond_i_fu_158_p2.read(), ap_const_lv1_0) && 
             !((ap_sig_bdd_103.read() && 
  esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it0.read())) || (ap_sig_bdd_110.read() && 
  esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read()))))) {
            ap_reg_ppiten_pp0_it1 = ap_const_logic_1;
        } else if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st2_fsm_1.read()) && 
                     esl_seteq<1,1,1>(exitcond5_i_fu_147_p2.read(), ap_const_lv1_0)) || 
                    (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg0_fsm_2.read()) && 
                     !((ap_sig_bdd_103.read() && 
  esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it0.read())) || (ap_sig_bdd_110.read() && 
  esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read()))) && 
                     !esl_seteq<1,1,1>(exitcond_i_fu_158_p2.read(), ap_const_lv1_0)))) {
            ap_reg_ppiten_pp0_it1 = ap_const_logic_0;
        }
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st5_fsm_3.read())) {
        p_1_i_reg_125 = i_V_reg_187.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st1_fsm_0.read()) && 
                !ap_sig_bdd_74.read())) {
        p_1_i_reg_125 = ap_const_lv12_0;
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg0_fsm_2.read()) && 
         esl_seteq<1,1,1>(exitcond_i_fu_158_p2.read(), ap_const_lv1_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it0.read()) && 
         !((ap_sig_bdd_103.read() && 
  esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it0.read())) || (ap_sig_bdd_110.read() && 
  esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read()))))) {
        p_i_reg_136 = j_V_fu_163_p2.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st2_fsm_1.read()) && 
                esl_seteq<1,1,1>(exitcond5_i_fu_147_p2.read(), ap_const_lv1_0))) {
        p_i_reg_136 = ap_const_lv12_0;
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st1_fsm_0.read()) && !ap_sig_bdd_74.read())) {
        cols_V_reg_178 = img_cols_V_dout.read();
        rows_V_reg_173 = img_rows_V_dout.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg0_fsm_2.read()) && !((ap_sig_bdd_103.read() && 
  esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it0.read())) || (ap_sig_bdd_110.read() && 
  esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read()))))) {
        exitcond_i_reg_192 = exitcond_i_fu_158_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st2_fsm_1.read())) {
        i_V_reg_187 = i_V_fu_152_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg0_fsm_2.read()) && esl_seteq<1,1,1>(exitcond_i_fu_158_p2.read(), ap_const_lv1_0) && !((ap_sig_bdd_103.read() && 
  esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it0.read())) || (ap_sig_bdd_110.read() && 
  esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read()))))) {
        tmp_data_V_reg_201 = INPUT_STREAM_TDATA.read();
    }
}

void newsob_AXIvideo2Mat_DMA::thread_INPUT_STREAM_TREADY() {
    if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg0_fsm_2.read()) && 
          esl_seteq<1,1,1>(exitcond_i_fu_158_p2.read(), ap_const_lv1_0) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it0.read()) && 
          !((ap_sig_bdd_103.read() && 
  esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it0.read())) || (ap_sig_bdd_110.read() && 
  esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read())))))) {
        INPUT_STREAM_TREADY = ap_const_logic_1;
    } else {
        INPUT_STREAM_TREADY = ap_const_logic_0;
    }
}

void newsob_AXIvideo2Mat_DMA::thread_ap_done() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_done_reg.read()) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st2_fsm_1.read()) && 
          !esl_seteq<1,1,1>(exitcond5_i_fu_147_p2.read(), ap_const_lv1_0)))) {
        ap_done = ap_const_logic_1;
    } else {
        ap_done = ap_const_logic_0;
    }
}

void newsob_AXIvideo2Mat_DMA::thread_ap_idle() {
    if ((!esl_seteq<1,1,1>(ap_const_logic_1, ap_start.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st1_fsm_0.read()))) {
        ap_idle = ap_const_logic_1;
    } else {
        ap_idle = ap_const_logic_0;
    }
}

void newsob_AXIvideo2Mat_DMA::thread_ap_ready() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st2_fsm_1.read()) && 
         !esl_seteq<1,1,1>(exitcond5_i_fu_147_p2.read(), ap_const_lv1_0))) {
        ap_ready = ap_const_logic_1;
    } else {
        ap_ready = ap_const_logic_0;
    }
}

void newsob_AXIvideo2Mat_DMA::thread_ap_sig_bdd_103() {
    ap_sig_bdd_103 = (esl_seteq<1,1,1>(INPUT_STREAM_TVALID.read(), ap_const_logic_0) && esl_seteq<1,1,1>(exitcond_i_fu_158_p2.read(), ap_const_lv1_0));
}

void newsob_AXIvideo2Mat_DMA::thread_ap_sig_bdd_110() {
    ap_sig_bdd_110 = (esl_seteq<1,1,1>(img_data_stream_V_full_n.read(), ap_const_logic_0) && esl_seteq<1,1,1>(exitcond_i_reg_192.read(), ap_const_lv1_0));
}

void newsob_AXIvideo2Mat_DMA::thread_ap_sig_bdd_137() {
    ap_sig_bdd_137 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(3, 3));
}

void newsob_AXIvideo2Mat_DMA::thread_ap_sig_bdd_23() {
    ap_sig_bdd_23 = esl_seteq<1,1,1>(ap_CS_fsm.read().range(0, 0), ap_const_lv1_1);
}

void newsob_AXIvideo2Mat_DMA::thread_ap_sig_bdd_74() {
    ap_sig_bdd_74 = (esl_seteq<1,1,1>(img_rows_V_empty_n.read(), ap_const_logic_0) || esl_seteq<1,1,1>(img_cols_V_empty_n.read(), ap_const_logic_0) || esl_seteq<1,1,1>(img_rows_V_out_full_n.read(), ap_const_logic_0) || esl_seteq<1,1,1>(img_cols_V_out_full_n.read(), ap_const_logic_0) || esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1));
}

void newsob_AXIvideo2Mat_DMA::thread_ap_sig_bdd_86() {
    ap_sig_bdd_86 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(1, 1));
}

void newsob_AXIvideo2Mat_DMA::thread_ap_sig_bdd_97() {
    ap_sig_bdd_97 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(2, 2));
}

void newsob_AXIvideo2Mat_DMA::thread_ap_sig_cseq_ST_pp0_stg0_fsm_2() {
    if (ap_sig_bdd_97.read()) {
        ap_sig_cseq_ST_pp0_stg0_fsm_2 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_pp0_stg0_fsm_2 = ap_const_logic_0;
    }
}

void newsob_AXIvideo2Mat_DMA::thread_ap_sig_cseq_ST_st1_fsm_0() {
    if (ap_sig_bdd_23.read()) {
        ap_sig_cseq_ST_st1_fsm_0 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st1_fsm_0 = ap_const_logic_0;
    }
}

void newsob_AXIvideo2Mat_DMA::thread_ap_sig_cseq_ST_st2_fsm_1() {
    if (ap_sig_bdd_86.read()) {
        ap_sig_cseq_ST_st2_fsm_1 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st2_fsm_1 = ap_const_logic_0;
    }
}

void newsob_AXIvideo2Mat_DMA::thread_ap_sig_cseq_ST_st5_fsm_3() {
    if (ap_sig_bdd_137.read()) {
        ap_sig_cseq_ST_st5_fsm_3 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st5_fsm_3 = ap_const_logic_0;
    }
}

void newsob_AXIvideo2Mat_DMA::thread_exitcond5_i_fu_147_p2() {
    exitcond5_i_fu_147_p2 = (!p_1_i_reg_125.read().is_01() || !rows_V_reg_173.read().is_01())? sc_lv<1>(): sc_lv<1>(p_1_i_reg_125.read() == rows_V_reg_173.read());
}

void newsob_AXIvideo2Mat_DMA::thread_exitcond_i_fu_158_p2() {
    exitcond_i_fu_158_p2 = (!p_i_reg_136.read().is_01() || !cols_V_reg_178.read().is_01())? sc_lv<1>(): sc_lv<1>(p_i_reg_136.read() == cols_V_reg_178.read());
}

void newsob_AXIvideo2Mat_DMA::thread_i_V_fu_152_p2() {
    i_V_fu_152_p2 = (!p_1_i_reg_125.read().is_01() || !ap_const_lv12_1.is_01())? sc_lv<12>(): (sc_biguint<12>(p_1_i_reg_125.read()) + sc_biguint<12>(ap_const_lv12_1));
}

void newsob_AXIvideo2Mat_DMA::thread_img_cols_V_out_din() {
    img_cols_V_out_din = img_cols_V_dout.read();
}

void newsob_AXIvideo2Mat_DMA::thread_img_cols_V_out_write() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st1_fsm_0.read()) && 
         !ap_sig_bdd_74.read())) {
        img_cols_V_out_write = ap_const_logic_1;
    } else {
        img_cols_V_out_write = ap_const_logic_0;
    }
}

void newsob_AXIvideo2Mat_DMA::thread_img_cols_V_read() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st1_fsm_0.read()) && 
         !ap_sig_bdd_74.read())) {
        img_cols_V_read = ap_const_logic_1;
    } else {
        img_cols_V_read = ap_const_logic_0;
    }
}

void newsob_AXIvideo2Mat_DMA::thread_img_data_stream_V_din() {
    img_data_stream_V_din = tmp_data_V_reg_201.read();
}

void newsob_AXIvideo2Mat_DMA::thread_img_data_stream_V_write() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg0_fsm_2.read()) && 
         esl_seteq<1,1,1>(exitcond_i_reg_192.read(), ap_const_lv1_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read()) && 
         !((ap_sig_bdd_103.read() && 
  esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it0.read())) || (ap_sig_bdd_110.read() && 
  esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read()))))) {
        img_data_stream_V_write = ap_const_logic_1;
    } else {
        img_data_stream_V_write = ap_const_logic_0;
    }
}

void newsob_AXIvideo2Mat_DMA::thread_img_rows_V_out_din() {
    img_rows_V_out_din = img_rows_V_dout.read();
}

void newsob_AXIvideo2Mat_DMA::thread_img_rows_V_out_write() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st1_fsm_0.read()) && 
         !ap_sig_bdd_74.read())) {
        img_rows_V_out_write = ap_const_logic_1;
    } else {
        img_rows_V_out_write = ap_const_logic_0;
    }
}

void newsob_AXIvideo2Mat_DMA::thread_img_rows_V_read() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st1_fsm_0.read()) && 
         !ap_sig_bdd_74.read())) {
        img_rows_V_read = ap_const_logic_1;
    } else {
        img_rows_V_read = ap_const_logic_0;
    }
}

void newsob_AXIvideo2Mat_DMA::thread_j_V_fu_163_p2() {
    j_V_fu_163_p2 = (!p_i_reg_136.read().is_01() || !ap_const_lv12_1.is_01())? sc_lv<12>(): (sc_biguint<12>(p_i_reg_136.read()) + sc_biguint<12>(ap_const_lv12_1));
}

void newsob_AXIvideo2Mat_DMA::thread_ap_NS_fsm() {
    switch (ap_CS_fsm.read().to_uint64()) {
        case 1 : 
            if (!ap_sig_bdd_74.read()) {
                ap_NS_fsm = ap_ST_st2_fsm_1;
            } else {
                ap_NS_fsm = ap_ST_st1_fsm_0;
            }
            break;
        case 2 : 
            if (!esl_seteq<1,1,1>(exitcond5_i_fu_147_p2.read(), ap_const_lv1_0)) {
                ap_NS_fsm = ap_ST_st1_fsm_0;
            } else {
                ap_NS_fsm = ap_ST_pp0_stg0_fsm_2;
            }
            break;
        case 4 : 
            if (!(esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it0.read()) && !((ap_sig_bdd_103.read() && 
  esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it0.read())) || (ap_sig_bdd_110.read() && 
  esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read()))) && !esl_seteq<1,1,1>(exitcond_i_fu_158_p2.read(), ap_const_lv1_0))) {
                ap_NS_fsm = ap_ST_pp0_stg0_fsm_2;
            } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it0.read()) && !((ap_sig_bdd_103.read() && 
  esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it0.read())) || (ap_sig_bdd_110.read() && 
  esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read()))) && !esl_seteq<1,1,1>(exitcond_i_fu_158_p2.read(), ap_const_lv1_0))) {
                ap_NS_fsm = ap_ST_st5_fsm_3;
            } else {
                ap_NS_fsm = ap_ST_pp0_stg0_fsm_2;
            }
            break;
        case 8 : 
            ap_NS_fsm = ap_ST_st2_fsm_1;
            break;
        default : 
            ap_NS_fsm = "XXXX";
            break;
    }
}

}

